force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Peer_Reviewer__c/Peer_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Peer Reviewer</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Peer Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Peer Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Peer_Reviewer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Peer Reviewers</relationshipLabel>
    <relationshipName>Peer_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Peer_Review_SelectionCTRLTest.cls
@isTest
public class Peer_Review_SelectionCTRLTest{
    @testSetup static void methodName() {
        EmailTemplate et = new EmailTemplate(); 
        et.isActive = true; 
        et.Name = 'testTemplate'; 
        et.DeveloperName = 'testTemplate' + System.now().getTime(); 
        et.TemplateType = 'text'; 
        et.FolderId = UserInfo.getUserId(); 
        et.Body = 'test'; 
        
        insert et; 
    }
    @isTest
    public static void unitTest(){
        
        Grants__c gnt= new Grants__c();
        gnt.Comments__c='Teting Sample';
        insert gnt;
        
        Peer_Reviewer__c pr = new Peer_Reviewer__c(First_Name__c = 't' , Last_Name__c = 'l', Email__c = 'test@gmail.com');
        insert pr;
        Peer_Review_SelectionCTRL obj = new Peer_Review_SelectionCTRL();
        
        obj.selectedTemplate = [SELECT Id FROM EmailTemplate LIMIT 1].Id;
        obj.selectedPeerReviewerId = pr.Id;
        
        obj.getTemplates() ;
        
        obj.fatchGrantRecords();
        
        obj.selectGrantRecord();
        obj.previous();
        obj.changeEvent();
        for(Peer_Review_SelectionCTRL.Option op : obj.peerReviewerOption ){
            op.isSelected = true;
        }
        obj.next();
        for(Peer_Review_SelectionCTRL.Option  o : obj.grantRecordList){
            o.isSelected = true;
        }
        obj.nextToTemplateView();
        obj.changeEventNext();
        obj.submit();
        obj.previousToTemplateView();
    }
}