force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Details__c/Education_Details__c.object-meta.xml
<CustomObject>
    <label>Education Details</label>
    <nameField>
        <displayFormat>EDU-{00000}</displayFormat>
        <label>Education Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Details__c/fields/CGPA_Division__c.field-meta.xml
<CustomField>
    <fullName>CGPA_Division__c</fullName>
    <label>CGPA/Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Likely_date_of_completion__c.field-meta.xml
<CustomField>
    <fullName>Likely_date_of_completion__c</fullName>
    <label>Likely date of completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Pursuing_Higher_Degree__c.field-meta.xml
<CustomField>
    <fullName>Pursuing_Higher_Degree__c</fullName>
    <description>Are you pursuing a higher degree (PhD, MD or equivalent) or academic course?</description>
    <inlineHelpText>Other Degree gives the option to enter Pursuing Degree</inlineHelpText>
    <label>Pursuing Higher Degree?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
            <value>
                <fullName>true</fullName>
                <isActive>false</isActive>
                <label>true</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Research_Summary_During_Highest_Degree__c.field-meta.xml
<CustomField>
    <fullName>Research_Summary_During_Highest_Degree__c</fullName>
    <label>Research Summary During Highest Degree</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Education Details</relationshipLabel>
    <relationshipName>Education_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_Other_Degree__c.field-meta.xml
<CustomField>
    <fullName>Specify_Other_Degree__c</fullName>
    <label>Specify Other Degree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_the_pursuing_degree__c.field-meta.xml
<CustomField>
    <fullName>Specify_the_pursuing_degree__c</fullName>
    <label>Specify the pursuing degree</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MPH</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>MBBS</fullName>
            </value>
            <value>
                <fullName>MD-PhD</fullName>
            </value>
            <value>
                <fullName>Other Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_the_University__c.field-meta.xml
<CustomField>
    <fullName>Specify_the_University__c</fullName>
    <label>Specify the University</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Title_of_thesis_Dissertation__c.field-meta.xml
<CustomField>
    <fullName>Title_of_thesis_Dissertation__c</fullName>
    <label>Title of thesis/Dissertation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <label>University</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employment_Details__c/Employment_Details__c.object-meta.xml
<CustomObject>
    <label>Employment Details</label>
    <nameField>
        <displayFormat>EMP-{00000}</displayFormat>
        <label>Employment Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employment_Details__c/fields/I_am_currently_working_here__c.field-meta.xml
<CustomField>
    <fullName>I_am_currently_working_here__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I am currently working here</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employment_Details__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employment_Details__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Employment Details</relationshipLabel>
    <relationshipName>Employment_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employment_Details__c/fields/Roles_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Roles_Responsibilities__c</fullName>
    <label>Roles &amp; Responsibilities</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Institution__c/Institution__c.object-meta.xml
<CustomObject>
    <label>Institution</label>
    <nameField>
        <displayFormat>INS-{000000}</displayFormat>
        <label>Institution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institution__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Keywords__c/Keywords__c.object-meta.xml
<CustomObject>
    <label>Keyword</label>
    <nameField>
        <displayFormat>K-{000}</displayFormat>
        <label>Keyword</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Keywords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Keywords__c/fields/Keyword_Name__c.field-meta.xml
<CustomField>
    <fullName>Keyword_Name__c</fullName>
    <label>Keyword Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Keywords__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Keywords</relationshipLabel>
    <relationshipName>Keywords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/Reviewer__c.object-meta.xml
<CustomObject>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Reviewer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer__c/fields/Alternate_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Phone_Number__c</fullName>
    <label>Alternate Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Reviewer_Type__c.field-meta.xml
<CustomField>
    <fullName>Reviewer_Type__c</fullName>
    <label>Reviewer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ex-Grantee</fullName>
            </value>
            <value>
                <fullName>Peer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer_Domain_Tag__c/Reviewer_Domain_Tag__c.object-meta.xml
<CustomObject>
    <label>Reviewer Domain Tag</label>
    <nameField>
        <label>Reviewer Domain Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviewer Domain Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer_Domain_Tag__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Reviewer Domain Tags</relationshipLabel>
    <relationshipName>Reviewer_Domain_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getProfileDetails.cls
@RestResource(urlMapping='/getProfileDetails')
global with sharing class getProfileDetails {

    @HttpGet
    global static ResponseWrapper doGet() {

        ResponseWrapper response = new ResponseWrapper();

        try {
            RestRequest req = RestContext.request;
            String reviewerId = req.params.get('Reviewer__c');
            String reviewerType = req.params.get('reviewerType');
            System.debug('Reviewer Id = ' + reviewerId);
            System.debug('Reviewer Type = ' + reviewerType);

            if (String.isBlank(reviewerId)) {
                response.success = false;
                response.message = 'Reviewer Id is required';
                return response;
            }

            // ---- Query Reviewer fields + related Education, Employment, Keywords & Domain Tags ----
            if(reviewerType == 'Peer'){
                List<Reviewer__c> reviewers = [
                    SELECT Id, Title__c, First_Name__c, Last_Name__c, Department__c, Alternate_Phone_Number__c,Mobile_Number__c,Designation__c,Email_Address__c,
                        Organisation__r.Name,State_Province__c,Reviewer_Type__c,Country__c, City__c,
                        (SELECT Id, Qualification__c, Institution__c, University__c, Start_Date__c,CGPA_Division__c,
                                End_Date__c, Specify_the_University__c, Specify_Other_Degree__c,
                                Specify_the_pursuing_degree__c, Pursuing_Higher_Degree__c,
                                Likely_date_of_completion__c, Title_of_thesis_Dissertation__c,
                                Research_Summary_During_Highest_Degree__c
                            FROM Education_Details__r
                            ORDER BY End_Date__c DESC),
                        (SELECT Id, Organisation__c, Position__c, Roles_Responsibilities__c,
                                Start_Date__c, End_Date__c, I_am_currently_working_here__c
                            FROM Employment_Details__r
                            ORDER BY Start_Date__c DESC),
                        (SELECT Id, Keyword_Name__c
                            FROM keywords__r
                            ORDER BY Keyword_Name__c DESC),
                            (SELECT Id, Name
                            FROM Reviewer_Domain_Tags__r
                            ORDER BY Name DESC)
                    FROM Reviewer__c
                    WHERE Id = :reviewerId And Reviewer_Type__c = :reviewerType
                    LIMIT 1
                ];
                 if (reviewers.isEmpty()) {
                    response.success = false;
                    response.message = 'Peer Reviewer not found';
                    return response;
                }
                
                    Reviewer__c rev = reviewers[0];

                    // ---- Build wrapper ----
                    response.success = true;
                    response.message = 'Success';
                    response.reviewDetails = wrapReviewer(rev);
                    response.educationDetails = wrapEducationDetails(rev.Education_Details__r);
                    response.employmentDetails = wrapEmploymentDetails(rev.Employment_Details__r);
                    response.keywordDetails = wrapKeywordDetails(rev.keywords__r);
                    response.domainTagsDetails = wrapDomainDetails(rev.Reviewer_Domain_Tags__r);
            }
            if(reviewerType != 'Peer'){
                List<Reviewer__c> reviewers = [
                    SELECT Id, Title__c, First_Name__c, Last_Name__c, Department__c, Alternate_Phone_Number__c,Mobile_Number__c,Designation__c,Email_Address__c,
                        Organisation__r.Name,State_Province__c,Reviewer_Type__c,Country__c, City__c,
                        (SELECT Id, Qualification__c, Institution__c, University__c, Start_Date__c,CGPA_Division__c,
                                End_Date__c, Specify_the_University__c, Specify_Other_Degree__c,
                                Specify_the_pursuing_degree__c, Pursuing_Higher_Degree__c,
                                Likely_date_of_completion__c, Title_of_thesis_Dissertation__c,
                                Research_Summary_During_Highest_Degree__c
                            FROM Education_Details__r
                            ORDER BY End_Date__c DESC),
                        (SELECT Id, Organisation__c, Position__c, Roles_Responsibilities__c,
                                Start_Date__c, End_Date__c, I_am_currently_working_here__c
                            FROM Employment_Details__r
                            ORDER BY Start_Date__c DESC),
                        (SELECT Id, Keyword_Name__c
                            FROM keywords__r
                            ORDER BY Keyword_Name__c DESC),
                            (SELECT Id, Name
                            FROM Reviewer_Domain_Tags__r
                            ORDER BY Name DESC)
                    FROM Reviewer__c
                    WHERE Id = :reviewerId 
                    LIMIT 1
                ];
                 if (reviewers.isEmpty()) {
                    response.success = false;
                    response.message = 'Ex Grantee Reviewer not found';
                    return response;
                }
                
            Reviewer__c rev = reviewers[0];

            // ---- Build wrapper ----
            response.success = true;
            response.message = 'Success';
            response.reviewDetails = wrapReviewer(rev);
            response.educationDetails = wrapEducationDetails(rev.Education_Details__r);
            response.employmentDetails = wrapEmploymentDetails(rev.Employment_Details__r);
            response.keywordDetails = wrapKeywordDetails(rev.keywords__r);
            response.domainTagsDetails = wrapDomainDetails(rev.Reviewer_Domain_Tags__r);
            }
        } catch (Exception e) {
            response.success = false;
            response.message = 'Error: ' + e.getMessage();
        }

        return response;
    }

    // ---- Helper: map Reviewer__c sObject to typed wrapper ----
    private static ReviewerWrapper wrapReviewer(Reviewer__c rev) {
        ReviewerWrapper rw = new ReviewerWrapper();
        rw.id = rev.Id;
        rw.title = rev.Title__c;
        rw.firstName = rev.First_Name__c;
        rw.lastName = rev.Last_Name__c;
        rw.email = rev.Email_Address__c;
        rw.phone = rev.Mobile_Number__c;
        rw.reviewerType = rev.Reviewer_Type__c;
        rw.position = rev.Designation__c;
        rw.department = rev.Department__c;
        rw.organisationName = rev.Organisation__r?.Name;
        rw.city = rev.City__c;
        rw.state = rev.State_Province__c;
        rw.country = rev.Country__c;
        rw.alternatePhoneNumber = rev.Alternate_Phone_Number__c;
        return rw;
    }

    // ---- Helper: map Education_Details__c list to typed wrapper list ----
    private static List<EducationDetailsWrapper> wrapEducationDetails(List<Education_Details__c> records) {
        List<EducationDetailsWrapper> wrappedList = new List<EducationDetailsWrapper>();

        for (Education_Details__c edu : records) {
            EducationDetailsWrapper ew = new EducationDetailsWrapper();
            ew.educationId = edu.Id;
            ew.qualification = edu.Qualification__c;
            ew.institution = edu.Institution__c;
            ew.university = edu.University__c;
            ew.startDate = edu.Start_Date__c;
            ew.endDate = edu.End_Date__c;
            ew.titleOfThesisDissertation = edu.Title_of_thesis_Dissertation__c;
            ew.cgpaGrade = edu.CGPA_Division__c;
            ew.researchSummaryDuringHighestDegree = edu.Research_Summary_During_Highest_Degree__c;
            wrappedList.add(ew);
        }

        return wrappedList;
    }

    // ---- Helper: map Employment_Details__c list to typed wrapper list ----
    private static List<EmploymentDetailsWrapper> wrapEmploymentDetails(List<Employment_Details__c> records) {
        List<EmploymentDetailsWrapper> wrappedList = new List<EmploymentDetailsWrapper>();

        for (Employment_Details__c emp : records) {
            EmploymentDetailsWrapper ew = new EmploymentDetailsWrapper();
            ew.employmentId = emp.Id;
            ew.organisation = emp.Organisation__c;
            ew.position = emp.Position__c;
            ew.description = emp.Roles_Responsibilities__c;
            ew.isCurrentlyWorking = emp.I_am_currently_working_here__c;
            ew.startDate = emp.Start_Date__c;
            ew.endDate = emp.End_Date__c;
            wrappedList.add(ew);
        }

        return wrappedList;
    }

    // ---- Helper: map Keywords__c list to typed wrapper list ----
    private static List<KeywordDetailsWrapper> wrapKeywordDetails(List<Keywords__c> records) {
        List<KeywordDetailsWrapper> wrappedList = new List<KeywordDetailsWrapper>();

        for (Keywords__c ky : records) {
            KeywordDetailsWrapper kw = new KeywordDetailsWrapper();
            kw.keywordDetailId = ky.Id;
            kw.keywordName = ky.Keyword_Name__c;
            wrappedList.add(kw);
        }

        return wrappedList;
    }

    // ---- Helper: map Reviewer_Domain_Tag__c list to typed wrapper list ----
    private static List<DomainTagsWrapper> wrapDomainDetails(List<Reviewer_Domain_Tag__c> records) {
        List<DomainTagsWrapper> wrappedList = new List<DomainTagsWrapper>();

        for (Reviewer_Domain_Tag__c dt : records) {
            DomainTagsWrapper dts = new DomainTagsWrapper();
            dts.domainTagsId = dt.Id;
            dts.domainName = dt.Name;
            wrappedList.add(dts);
        }

        return wrappedList;
    }

    // ---- Wrapper classes ----
    global class ResponseWrapper {
        global Boolean success;
        global String message;
        global ReviewerWrapper reviewDetails;
        global List<EducationDetailsWrapper> educationDetails;
        global List<EmploymentDetailsWrapper> employmentDetails;
        global List<KeywordDetailsWrapper> keywordDetails;
        global List<DomainTagsWrapper> domainTagsDetails;
    }

    global class ReviewerWrapper {
        global String id;
        global String title;
        global String firstName;
        global String lastName;
        global String email;
        global String phone;
        global String reviewerType;
        global String position;
        global String department;
        global String organisationName;
        global String city;
        global String state;
        global String country;
        global String alternatePhoneNumber;
        // PLACEHOLDER: additional fields
    }

    global class EducationDetailsWrapper {
        global String educationId;
        global String qualification;
        global String institution;
        global String university;
        global Date startDate;
        global Date endDate;
        global String cgpaGrade;
        global Date likelyDateOfCompletion;
        global String titleOfThesisDissertation;
        global String researchSummaryDuringHighestDegree;
    }

    global class EmploymentDetailsWrapper {
        global String employmentId;
        global String organisation;
        global String position;
        global String description;
        global Boolean isCurrentlyWorking;
        global Date startDate;
        global Date endDate;
    }

    global class DomainTagsWrapper {
        global String domainTagsId;
        global String domainName;
    }

    global class KeywordDetailsWrapper {
        global String keywordDetailId;
        global String keywordName;
    }
}