force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Details__c/Education_Details__c.object-meta.xml
<CustomObject>
    <label>Education Details</label>
    <nameField>
        <displayFormat>EDU-{00000}</displayFormat>
        <label>Education Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Details__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Education Details</relationshipLabel>
    <relationshipName>Education_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Department_School_Division__c.field-meta.xml
<CustomField>
    <fullName>Department_School_Division__c</fullName>
    <label>Department / School / Division</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Likely_date_of_completion__c.field-meta.xml
<CustomField>
    <fullName>Likely_date_of_completion__c</fullName>
    <label>Likely date of completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Pursuing_Higher_Degree__c.field-meta.xml
<CustomField>
    <fullName>Pursuing_Higher_Degree__c</fullName>
    <description>Are you pursuing a higher degree (PhD, MD or equivalent) or academic course?</description>
    <inlineHelpText>Other Degree gives the option to enter Pursuing Degree</inlineHelpText>
    <label>Pursuing Higher Degree?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>false</fullName>
                <isActive>false</isActive>
                <label>false</label>
            </value>
            <value>
                <fullName>true</fullName>
                <isActive>false</isActive>
                <label>true</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Qualification__c.field-meta.xml
<CustomField>
    <fullName>Qualification__c</fullName>
    <label>Qualification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_Other_Degree__c.field-meta.xml
<CustomField>
    <fullName>Specify_Other_Degree__c</fullName>
    <label>Specify Other Degree</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_the_pursuing_degree__c.field-meta.xml
<CustomField>
    <fullName>Specify_the_pursuing_degree__c</fullName>
    <label>Specify the pursuing degree</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MPH</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>MBBS</fullName>
            </value>
            <value>
                <fullName>MD-PhD</fullName>
            </value>
            <value>
                <fullName>Other Degree</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Specify_the_University__c.field-meta.xml
<CustomField>
    <fullName>Specify_the_University__c</fullName>
    <label>Specify the University</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <label>Supervisor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/Title_of_thesis_Dissertation__c.field-meta.xml
<CustomField>
    <fullName>Title_of_thesis_Dissertation__c</fullName>
    <label>Title of thesis/Dissertation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Details__c/fields/University__c.field-meta.xml
<CustomField>
    <fullName>University__c</fullName>
    <label>University</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Institution__c/Institution__c.object-meta.xml
<CustomObject>
    <label>Institution</label>
    <nameField>
        <displayFormat>INS-{000000}</displayFormat>
        <label>Institution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institution__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AcademicHistoryDetailsAPI.cls
@RestResource(urlMapping='/academicHistoryDetails')
global without sharing class AcademicHistoryDetailsAPI {

    @HttpPost
    global static ResponseWrapper saveAcademicHistoryDetails() {

        ResponseWrapper response = new ResponseWrapper();

        try {

            String requestBody = RestContext.request.requestBody.toString();
            RequestWrapper req = (RequestWrapper)JSON.deserialize(requestBody, RequestWrapper.class);

            if (String.isBlank(req.contactId)) {
                response.success = false;
                response.message = 'Missing required field: applicantId.';
                response.totalInsertedRecords = 0;
                return response;
            }

            Education_Details__c edu = new Education_Details__c();

                edu.Contact__c = req.contactId;
                edu.Institution__c = req.institution;
                edu.Qualification__c = req.degree;
                edu.Subject__c = req.specialization;
                edu.Department_School_Division__c = req.grade;
                edu.Start_Date__c = req.admissionDate;
                edu.End_Date__c = req.passingDate;
                edu.University__c = req.university;
                edu.Pursuing_Higher_Degree__c = req.pursuingHigherDegree;
                edu.Specify_Other_Degree__c = req.otherDegree;
                edu.Specify_the_University__c = req.otherInstitution;

                if (String.isNotBlank(req.educationId)) {
                    edu.Id = req.educationId;
                }
    
            if (edu != null) {
                if (String.isNotBlank(req.educationId)) {
                    update edu;
                    response.success = true;
                    response.message = 'Academic history updated successfully.';
                    response.totalInsertedRecords = 1;
                    response.educationId = edu.Id;
                } else {
                    insert edu;
                    response.success = true;
                    response.message = 'Academic history inserted successfully.';
                    response.totalInsertedRecords = 1;
                    response.educationId = edu.Id;
                }
            }
        }
        catch (Exception ex) {
            response.success = false;
            response.message = 'An error occurred while saving details: ' + ex.getMessage();
            response.totalInsertedRecords = 0;
        }
        return response;
    }

    global class RequestWrapper {
        public String contactId;
        public String educationId;
        public String institution;
        public String degree;
        public String specialization;
        public String grade;
        public Date admissionDate;
        public Date passingDate;
        public String university;
        public String pursuingHigherDegree;
        public String specifyOtherDegree;
        public String otherInstitution;
        public String otherDegree;
    }

    global class ResponseWrapper {
        public Boolean success;
        public String message;
        public String educationId;
        public Integer totalInsertedRecords;
    }

}

// @RestResource(urlMapping='/academicHistoryDetails')
// global without sharing class AcademicHistoryDetailsAPI {
    
//     @HttpPost
//     global static ResponseWrapper saveAcademicHistoryDetails(){
        
//         ResponseWrapper response = new ResponseWrapper();
        
//         try{
//             String requestBody = RestContext.request.requestBody.toString();
//             RequestWrapper req = (RequestWrapper) JSON.deserialize(requestBody, RequestWrapper.class);
            
//             if(String.isBlank(req.contactId) || req.educationList == null || req.educationList.isEmpty()){
//                 response.success = false;
//                 response.message = 'Missing required fields: contactId or educationList.';
//                 return response;
//             }
            
//             List<Education_Details__c> eduDetailsToInsert = new List<Education_Details__c>();
            
//             for(EducationItem item : req.educationList){
                
//                 Education_Details__c edu = new Education_Details__c();
                
//                 edu.Contact__c = req.contactId;
//                 edu.Start_Date__c = item.fromDate;
//                 edu.End_Date__c = item.toDate;
//                 edu.Qualification__c = item.qualification;
//                 edu.Subject__c = item.subject;
//                 edu.Country__c = item.country;
//                 edu.Institution__c = item.institution;
//                 edu.Department_School_Division__c = item.department;
//                 edu.Supervisor__c = item.supervisor;
//                 edu.Pursuing_Higher_Degree__c = item.pursuingHigherDegree;
//                 edu.Specify_the_pursuing_degree__c = item.specifyHigherDegree;
//                 edu.Likely_date_of_completion__c = item.likelyDateOfCompletion;
//                 edu.Title_of_thesis_Dissertation__c = item.thesisDissertationTitle;
                
//                 eduDetailsToInsert.add(edu);
//             }
            
//             if(! eduDetailsToInsert.isEmpty()){
//                 insert eduDetailsToInsert;
//             }
            
//             response.success = true;
//             response.message = 'Academic history saved successfully.';
//             response.totalInsertedRecords = eduDetailsToInsert.size();
//         }
//         catch(Exception ex){
//             response.success = false;
//             response.message = 'An error occurred while saving details: ' + ex.getMessage();
//             response.totalInsertedRecords = 0;
//         }
        
//         return response;
        
//     }
    
//     global class RequestWrapper {
//         public String contactId;
//         public List<EducationItem> educationList;
//     }
    
//     global class EducationItem {     
//         public Date fromDate;
//         public Date toDate;
//         public String qualification;
//         public String subject;
//         public String country;
//         public String institution;
//         public String department;
//         public String supervisor;        
        
//         public String pursuingHigherDegree;
//         public String specifyHigherDegree;
//         public Date likelyDateOfCompletion;
//         public String thesisDissertationTitle;
//     }

//     global class ResponseWrapper {
//         public Boolean success;
//         public String message;
//         public Integer totalInsertedRecords;
//     }
    

    
    
// }