force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Display__c.field-meta.xml
<CustomField>
    <fullName>Display__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>LP1_Institution__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>LP1_Institution__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Human_participants__c.field-meta.xml
<CustomField>
    <fullName>Human_participants__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does your proposal include working with human participants, experiments with human stem cells, biological samples and/or personal data relating to living or dead persons? If yes, please tick as appropriate:</inlineHelpText>
    <label>Human participants</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Institutional_Ethics_Committee_IEC__c.field-meta.xml
<CustomField>
    <fullName>Institutional_Ethics_Committee_IEC__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will this work require approval from?[Institutional Ethics Committee (IEC)]</inlineHelpText>
    <label>Institutional Ethics Committee (IEC)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <formula>TEXT(LP1_Institution__r.Pincode__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Professor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (1)</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (2)</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (3)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Use_of_animals__c.field-meta.xml
<CustomField>
    <fullName>Use_of_animals__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does your proposal involve any of the following?</inlineHelpText>
    <label>Use of animals</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Institution__c/Institution__c.object-meta.xml
<CustomObject>
    <label>Institution</label>
    <nameField>
        <displayFormat>INS-{000000}</displayFormat>
        <label>Institution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institution__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Institution</fullName>
            </value>
            <value>
                <fullName>Co-Institution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/Investigator__c.object-meta.xml
<CustomObject>
    <label>Investigator</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Principal Investigator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigator__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Discipline_expertise__c.field-meta.xml
<CustomField>
    <fullName>Discipline_expertise__c</fullName>
    <label>Discipline/Expertise</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipName>Principal_Investigators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investigators</relationshipLabel>
    <relationshipName>Principal_Investigators</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Investigators_Type__c.field-meta.xml
<CustomField>
    <fullName>Investigators_Type__c</fullName>
    <label>Investigator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Coordinator 1</fullName>
                <isActive>false</isActive>
                <label>Coordinator 1</label>
            </value>
            <value>
                <fullName>Coordinator 2</fullName>
                <isActive>false</isActive>
                <label>Coordinator 2</label>
            </value>
            <value>
                <fullName>Coordinator 3</fullName>
                <isActive>false</isActive>
                <label>Coordinator 3</label>
            </value>
            <value>
                <fullName>Lead Principal Investigator</fullName>
                <isActive>false</isActive>
                <label>Lead Principal Investigator</label>
            </value>
            <value>
                <fullName>Programme Head</fullName>
                <isActive>false</isActive>
                <label>Programme Head</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Is_Programme_Head__c.field-meta.xml
<CustomField>
    <fullName>Is_Programme_Head__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Programme Head</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/ORCID_ID__c.field-meta.xml
<CustomField>
    <fullName>ORCID_ID__c</fullName>
    <label>ORCID ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Professor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Programme Head</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Other_Document__c/Other_Document__c.object-meta.xml
<CustomObject>
    <label>Other Document</label>
    <nameField>
        <displayFormat>OD-{000000}</displayFormat>
        <label>Other Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Document__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Other Documents</relationshipLabel>
    <relationshipName>Other_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TSGApplicationFormControllerTest.cls
@istest
public class TSGApplicationFormControllerTest{
    @isTest static void unitTestTSG(){
        Id devRecordTypeId = Schema.SObjectType.Grants__c.getRecordTypeInfosByName().get('Team Science Grants (TSG)').getRecordTypeId();
        TSGApplicationFormController.formInit(null, devRecordTypeId , null);
        Id grantId = [SELECT Id FROM Grants__c LIMIT 1].Id;
        
        Other_Document__c od = new Other_Document__c(Description__c = 'Test', Grants__c = grantId , Subject__c = 'subject');
        insert od;
        
        ContentVersion cv = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.jpg',
            VersionData = blob.valueof('Test Content Data'),
            IsMajorVersion = true
        );
        insert cv;
        
        ContentVersion contentVersionSelect = [SELECT Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId = od.id;                
        contentlink.ContentDocumentId = documents[0].Id;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
        Country__c co = new Country__c(Active__c = true, Country_Code__c = 'IN' , Display__c = true);
        insert co;
        
        Account acc = new Account(
            Name = 't',
            Department__c = 'd',
            Address__c = 'Address__c',
            City__c = 'City__c',
            Country__c = co.Id,
            Pincode__c = 54545454,
            Institution_Categories__c = 'Other'
        );
        insert acc;
        
        Investigator__c inv = new Investigator__c(
            Institution__c = acc.Id,
            Title__c= 'Mr.',
            First_Name__c = 'First_Name__c',
            Last_Name__c = 'Last_Name__c',
            Investigators_Type__c = 'Principal Investigator',
            Role__c = 'Role__c',
            Nationality__c = 'Nationality__c',
            Gender__c = 'Male',
            Email__c = 'test@gmil.com',
            Contact_Number__c = '12154545',
            Date_of_Birth__c = date.today(),
            Discipline_expertise__c = 'Discipline_expertise__c',
            ORCID_ID__c = '0000-0000-0000-0000',
            Grants__c = grantId 
        
        );
        insert inv;
        Investigator__c inv2 = new Investigator__c(
            Institution__c = acc.Id,
            Title__c= 'Mr.',
            First_Name__c = 'First_Name__c',
            Last_Name__c = 'Last_Name__c',
            Type__c = ' Programme Head',
            Role__c = 'Role__c',
            Nationality__c = 'Nationality__c',
            Gender__c = 'Male',
            Email__c = 'test@gmil.com',
            Contact_Number__c = '12154545',
            Date_of_Birth__c = date.today(),
            Discipline_expertise__c = 'Discipline_expertise__c',
            ORCID_ID__c = '0000-0000-0000-0000',
            Grants__c = grantId ,
            Is_Programme_Head__c = true
        
        );
        insert inv2;
        
        TSGForm form = TSGApplicationFormController.formInit(grantId , devRecordTypeId , null);
        TSGApplicationFormController.editGrant(grantId);
        TSGApplicationFormController.upsertInvestigator(inv);
        
        form.grantRecord.Human_participants__c = true;
        form.grantRecord.Institutional_Ethics_Committee_IEC__c = true;
        form.grantRecord.Use_of_animals__c = true;
        String json = JSON.serialize(form );
        TSGApplicationFormController.addYearApex('2020', json);
        
        TSGApplicationFormController.saveData(json, 'step1', false);
        TSGApplicationFormController.saveData(json, 'step2', false);
        TSGApplicationFormController.saveData(json, 'step3', false);
        TSGApplicationFormController.saveData(json, 'step4', false);
        TSGApplicationFormController.saveData(json, 'step5', false);
        TSGApplicationFormController.saveData(json, 'step6', false);
        TSGApplicationFormController.saveData(json, 'step7', false);
        TSGApplicationFormController.saveData(json, 'step8', false);
        TSGApplicationFormController.saveData(json, 'step9', false);
        TSGApplicationFormController.saveData(json, 'step10', false);
        TSGApplicationFormController.saveData(json, 'step11', false);
        TSGApplicationFormController.saveData(json, 'step12', false);
        TSGApplicationFormController.saveData(json, 'step13', false);
        TSGApplicationFormController.saveData(json, 'step14', false);
        TSGApplicationFormController.saveData(json, 'step15', false);
        TSGApplicationFormController.saveData(json, 'step1', true);
        
        TSGApplicationFormController.submitGrant(grantId);
        
        Grants__c  grant = new Grants__c (Status__c = 'Ineligible', Id=grantId );
        update grant;
        
        TSGApplicationFormController.pass();
    }
}