force-app/main/default/objects/Assigned_Reviewer__c/Assigned_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Assigned Reviewer</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Assigned Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Assigned Reviewers</relationshipLabel>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignedReviewerTrigger_Test.cls
@isTest
public class AssignedReviewerTrigger_Test {
    public static testMethod void testOne(){
        Grants__c gnt= new Grants__c();
        gnt.Comments__c='Teting Sample';
        insert gnt;
        
        Assigned_Reviewer__c ar = new Assigned_Reviewer__c();
        ar.Assigned_User__c=userinfo.getuserId();
        ar.Grants__c=gnt.Id;
        insert ar;
        
        Assigned_Reviewer__c ar2 = new Assigned_Reviewer__c(id=ar.ID);
        ar2.Assigned_User__c=userinfo.getuserId();
        ar2.Grants__c=gnt.Id;
        delete ar2;
        
        undelete ar2;
    }
}