force-app/main/default/objects/Assigned_Reviewer__c/Assigned_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Assigned Reviewer</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Assigned Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Assigned Reviewers</relationshipLabel>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/fields/designation__c.field-meta.xml
<CustomField>
    <fullName>designation__c</fullName>
    <label>designation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/Peer_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Peer Reviewer</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Peer Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Peer Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Peer_Reviewer__c/fields/Created_User__c.field-meta.xml
<CustomField>
    <fullName>Created_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Created User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Peer_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Declined__c.field-meta.xml
<CustomField>
    <fullName>Declined__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Declined</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Peer Reviewers</fullName>
                <default>true</default>
                <label>Peer Reviewers</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>First_Name__c +&apos; &apos;+ Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Grant_Id_Selected__c.field-meta.xml
<CustomField>
    <fullName>Grant_Id_Selected__c</fullName>
    <label>Grant Id Selected</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Peer Reviewers</relationshipLabel>
    <relationshipName>Peer_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Is_User_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_User_Created__c</fullName>
    <formula>NOT(ISBLANK( Created_User__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is User Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Peer_Reviewer__c/fields/Verified_by_User__c.field-meta.xml
<CustomField>
    <fullName>Verified_by_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified by User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PeerReviewerApprovalVFController.cls
public class PeerReviewerApprovalVFController{
public boolean accept {get;set;}
public string reviewRecordId ;
public string submitErrorMessage {get;set;}
public boolean isAccepted {get;set;}
    
    public PeerReviewerApprovalVFController(){
        reviewRecordId = ApexPages.currentPage().getParameters().get('id');
        
        List<Peer_Reviewer__c> Peer_ReviewerList = [SELECT Id, Name, Declined__c , First_Name__c, Last_Name__c, Full_Name__c, Email__c, Created_User__c, Designation__c, Is_User_Created__c, Verified_by_User__c, Grant_Id_Selected__c FROM Peer_Reviewer__c WHERE Id = : reviewRecordId];
        isAccepted = true;
        if(!Peer_ReviewerList.isEmpty()){
            isAccepted = Peer_ReviewerList.get(0).Is_User_Created__c || Peer_ReviewerList.get(0).Declined__c ;
        }
    }
    public void declined(){
        update new Peer_Reviewer__c(Id=reviewRecordId, Declined__c = true);
        isAccepted = true;
    }
    public void acceptTerms(){
        try{
            List<Peer_Reviewer__c> Peer_ReviewerList = [SELECT Id, Name, Declined__c ,First_Name__c, Last_Name__c, Full_Name__c, Email__c, Created_User__c, Designation__c, Is_User_Created__c, Verified_by_User__c, Grant_Id_Selected__c FROM Peer_Reviewer__c WHERE Id = : reviewRecordId];
            List<Profile> profileList = [SELECT Id FROM Profile WHERE Name = : Label.Peer_Reviewer_Profile_Name];
            List<Assigned_Reviewer__c > shareList = new List<Assigned_Reviewer__c >();
            if(!profileList.isEmpty()){
                if(!Peer_ReviewerList.isEmpty()){
                    Peer_Reviewer__c pr = Peer_ReviewerList.get(0);
                    contact con = null;
                    if(Label.Is_Portal_Peer_Reviewer_Profile == 'true'){
                        List<Contact> contacts = [SELECT Id FROM Contact WHERE Email =: pr.Email__c AND FirstName =: pr.First_Name__c AND LastName =: pr.Last_Name__c];
                        if(!contacts.isEmpty()){
                            con = contacts.get(0);
                        }else{
                            con  = new Contact(
                                Email = pr.Email__c,
                                FirstName = pr.First_Name__c,
                                LastName = pr.Last_Name__c
                            );
                            if(!Test.isRunningTest() ) insert con  ;
                        }
                    }
                    
                    User userRegistration = new User();
                    userRegistration.Email = pr.Email__c;
                    userRegistration.FirstName = pr.First_Name__c;
                    userRegistration.LastName = pr.Last_Name__c;
                    userRegistration.Username = pr.Email__c;
                    userRegistration.profileId = profileList.get(0).Id;
                    userRegistration.Alias = 'IAIN';
                    userRegistration.EmailEncodingKey='UTF-8';
                    userRegistration.LanguageLocaleKey='en_US';
                    userRegistration.LocaleSidKey='en_US';
                    userRegistration.TimeZoneSidKey='Asia/Kolkata';
                    if(con != null) userRegistration.ContactId=con.Id; userRegistration.communityNickname = pr.Last_Name__c + '_' + Math.random();

                    if(!Test.isRunningTest() ) Database.insert(userRegistration);
                    
                    pr.Created_User__c = userRegistration.Id;
                    pr.Verified_by_User__c = true;
                    update pr;
                    
                    string userId = userRegistration.Id;
                    List<String> grantIdList = pr.Grant_Id_Selected__c != null ? pr.Grant_Id_Selected__c.split(';') : new List<String>();
                    if(!grantIdList.isEmpty()){
                        for(String id : grantIdList){
                            Assigned_Reviewer__c sRd = new Assigned_Reviewer__c(Assigned_User__c = userId , Grants__c = id);
                            shareList.add(sRd);
                        }
                        
                        if(!shareList.isEmpty()) database.insert(shareList, false);
                    }
                    if(!Test.isRunningTest() ) System.resetPassword(Id.valueOf(userId), true);
                    isAccepted = true;
                }
            }
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage()));
        }
    }
}