force-app/main/default/objects/Assigned_Reviewer__c/Assigned_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Assigned Reviewer</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Assigned Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Assigned Reviewers</relationshipLabel>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignedReviewerTriggerHandler.cls
public class AssignedReviewerTriggerHandler{
    
    
    public void checkDuplicateUser(){
        List<Assigned_Reviewer__c > newList = (List<Assigned_Reviewer__c > ) trigger.new;
        Set<Id> grantIdSet = new Set<Id>();
        Set<Id> userIdSet = new Set<Id>();
        Set<String> keyIdSet = new Set<String>();
        for(Assigned_Reviewer__c  ar : newList){
            if(ar.Assigned_User__c != null){
                userIdSet.add(ar.Assigned_User__c );
            }
            if(ar.Grants__c != null){
                grantIdSet.add(ar.Grants__c );
            }
        }
        List<Assigned_Reviewer__c > existingARList = [SELECT Id, Assigned_User__c, Grants__c FROM Assigned_Reviewer__c WHERE Assigned_User__c IN: userIdSet AND Grants__c IN : grantIdSet AND Id NOT IN : newList];
        for(Assigned_Reviewer__c  ar : existingARList){
            keyIdSet.add(ar.Grants__c +''+ar.Assigned_User__c);
        }
        
        for(Assigned_Reviewer__c  ar : newList){
            string key = ar.Grants__c +''+ar.Assigned_User__c;
            if(keyIdSet.contains(key)){
                ar.Assigned_User__c.addError('The value you selected is already in the sharing.');
            }
        }
    }
    
    public void createManualSharing(){
        List<Assigned_Reviewer__c > newList = (List<Assigned_Reviewer__c >) trigger.new;
        List<Assigned_Reviewer__c > oldList = (List<Assigned_Reviewer__c >) trigger.old;
        Map<Id,Assigned_Reviewer__c > oldMap = (Map<Id,Assigned_Reviewer__c >) trigger.oldMap;
        Set<String> whreClause = new Set<String>();
        List<Grants__Share > shareList = new List<Grants__Share >();
        if((Boolean) trigger.isInsert){
            for(Assigned_Reviewer__c ar : newList ){
                if(ar.Assigned_User__c != null  && ar.Grants__c != null){
                    Grants__Share sRd = manualShareRead(ar.Grants__c , ar.Assigned_User__c);
                    shareList.add(sRd);
                }
            }
        }else if((Boolean) trigger.isUpdate){
            for(Assigned_Reviewer__c ar : newList ){
                if(ar.Assigned_User__c != oldMap.get(ar.Id).Assigned_User__c || ar.Grants__c != oldMap.get(ar.Id).Grants__c ){
                    if(ar.Assigned_User__c != null  && ar.Grants__c != null){
                        Grants__Share sRd = manualShareRead(ar.Grants__c , ar.Assigned_User__c);
                        shareList.add(sRd);
                    }
                    whreClause.add(' (UserOrGroupId = \''+ar.Assigned_User__c+'\' AND ParentId = \''+ar.Grants__c+'\') ');
                    whreClause.add(' (UserOrGroupId = \''+oldMap.get(ar.Id).Assigned_User__c+'\' AND ParentId = \''+oldMap.get(ar.Id).Grants__c+'\') ');
                }
            }
        }else if((Boolean) trigger.isDelete){
            for(Assigned_Reviewer__c ar : oldList ){
                whreClause.add(' (UserOrGroupId = \''+ar.Assigned_User__c+'\' AND ParentId = \''+ar.Grants__c+'\') ');
            }
        }else if((Boolean) trigger.isUndelete){
            for(Assigned_Reviewer__c ar : newList ){
                if(ar.Assigned_User__c != null  && ar.Grants__c != null){
                    Grants__Share sRd = manualShareRead(ar.Grants__c , ar.Assigned_User__c);
                    shareList.add(sRd);
                }
            }
        }
        if(!whreClause.isEmpty()){
            List<String> wList = new List<String> ();
            wList.addAll(whreClause );
            String query = 'SELECT Id FROM Grants__Share WHERE '+String.Join(wList, ' OR ');
            system.debug('query  '+query );
            List<Grants__Share > sharingRecordList = database.query(query );
            if(!sharingRecordList.isEmpty()) database.delete(sharingRecordList , false);
        }
        
        if(!shareList.isEmpty()){
            database.insert(shareList, false);
        }
    }
    
    public static Grants__Share manualShareRead(Id recordId, Id userOrGroupId){
      Grants__Share jobShr  = new Grants__Share ();
      jobShr.ParentId = recordId;
      jobShr.UserOrGroupId = userOrGroupId;
      jobShr.AccessLevel = 'Read';
      jobShr.RowCause = Schema.Grants__Share.RowCause.Manual;
      
      return jobShr;
   }
}