force-app/main/default/objects/Assigned_Reviewer__c/Assigned_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Assigned Reviewer</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Assigned Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assigned Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assigned_Reviewer__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Assigned Reviewers</relationshipLabel>
    <relationshipName>Assigned_Reviewers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignReviewerController.cls
public class AssignReviewerController{
    
    @AuraEnabled
    public static SharingSettiing init(String recordId){
        List<Assigned_Reviewer__c> Assigned_ReviewerList = [SELECT Id, Name, Assigned_User__r.Name, Grants__c FROM Assigned_Reviewer__c WHERE Grants__c = : recordId];
        SharingSettiing ss = new SharingSettiing(Assigned_ReviewerList);
        return ss;
    }
    
    public class SharingSettiing{
        @AuraEnabled
        public List<Assigned_Reviewer__c> Assigned_ReviewerList;
        
        public SharingSettiing(List<Assigned_Reviewer__c> Assigned_ReviewerList){
            this.Assigned_ReviewerList = Assigned_ReviewerList;
        }
    }
    
    @AuraEnabled
    public static boolean apexDeleteRecord(String recordId){
        if(string.isNotBlank(recordId)){
            Id id = recordId;
            String ObjectName = id.getSObjectType()+'';
            sObject sObj = Schema.getGlobalDescribe().get(ObjectName).newSObject() ;
            sObj.put('Id',recordId);
            delete sObj; 
            return true;
        }
        return false;
    }
}