force-app/main/default/objects/Application_PDFs__c/Application_PDFs__c.object-meta.xml
<CustomObject>
    <label>Application PDF</label>
    <nameField>
        <displayFormat>APDF-{000000}</displayFormat>
        <label>Application PDF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application PDFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_PDFs__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Application PDFs</relationshipLabel>
    <relationshipName>Application_PDFs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/fields/Applicant_PDF_URL__c.field-meta.xml
<CustomField>
    <fullName>Applicant_PDF_URL__c</fullName>
    <label>Applicant PDF URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Generated_pdf_URL__c.field-meta.xml
<CustomField>
    <fullName>Generated_pdf_URL__c</fullName>
    <label>Generated pdf URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Is_Admin__c.field-meta.xml
<CustomField>
    <fullName>Is_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Is_PDF_Generated__c.field-meta.xml
<CustomField>
    <fullName>Is_PDF_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is PDF Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <formula>IF(RecordType.DeveloperName =&apos;CRC&apos;, &apos;IA&apos; + &apos;/&apos; + &apos;CRC&apos; + &apos;/&apos; 
			+RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))),2) + &apos;/&apos; + &apos;1&apos;+&apos;/&apos;+Reference__c,
IF(RecordType.DeveloperName =&apos;Team_Science_Grants_TSG&apos;,&apos;IA&apos; + &apos;/&apos; + &apos;TSG&apos; + &apos;/&apos; 
			+RIGHT(TEXT(YEAR(DATEVALUE(CreatedDate))),2)+ &apos;/&apos; + &apos;1&apos; + &apos;/&apos; +Reference__c,&apos;0&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reference Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreatePDFController.cls
public class CreatePDFController{
    
    @AuraEnabled
    public static boolean createApplicationPDF(String recordId){
        if(String.isNotBlank(recordId)){
            Application_PDFs__c pdf = new Application_PDFs__c(Grants__c = recordId);
            insert pdf;
            String pdfRecordId = pdf.Id;
            TSGForm form = new TSGForm(recordId);
            List<ContentDocumentLink> conList = [SELECT ContentDocumentId,ContentDocument.Title,ContentDocument.ContentModifiedDate, ContentDocument.ContentSize FROM ContentDocumentLink WHERE ContentDocumentId=:form.contentDocumentIdList];
            List<ContentDocumentLink> conClone = new List<ContentDocumentLink>();
            for(ContentDocumentLink file: conList){
                ContentDocumentLink newclnk = file.clone();
                newclnk.LinkedEntityId = pdfRecordId;
                newclnk.ShareType = 'V';
                conClone.add(newclnk);
            }
            
            database.insert(conClone, false);
            
            PageReference pref = page.GrantApplicationPDF;
            pref.getParameters().put('id',recordId);
            blob pdfBlob;
            if(!test.isRunningTest()) pdfBlob = pref.getContent(); 
            ContentVersion conVer = new ContentVersion();
            conVer.ContentLocation = 'S';
            conVer.PathOnClient = form.grantRecord.Reference_Number__c+'.pdf';
            conVer.Title = form.grantRecord.Reference_Number__c;
            conVer.VersionData = pdfBlob;
            if(!test.isRunningTest()) insert conVer; 
            
            Id conDoc2;
            if(!test.isRunningTest()) conDoc2 = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:conVer.Id].ContentDocumentId;
            ContentDocumentLink conDocLink = New ContentDocumentLink();
            conDocLink.LinkedEntityId = pdfRecordId;
            conDocLink.ContentDocumentId = conDoc2;
            conDocLink.shareType = 'V';
            if(!test.isRunningTest()) insert conDocLink;
        }
        system.debug('Enter in method');
        return false;
    }
    @AuraEnabled
    public static boolean createApplicationPDFBySite(String recordId){
        if(String.isNotBlank(recordId)){
            List<Grants__c> grantList = [SELECT Id,Is_Admin__c,Is_PDF_Generated__c FROM Grants__c WHERE Id =: recordId];
            if(!grantList.isEmpty()){
                grantList[0].Generated_pdf_URL__c = '';
                grantList[0].Is_Admin__c = true;
                update grantList;
                Id batchJobId = Database.executeBatch(new BatchCreateGrantPDF(recordId), 1);
                return true;
            }
        }
        system.debug('Enter in method');
        return false;
    }
    @AuraEnabled
    public static boolean createApplicationPDFBySiteApplicant(String recordId){
        if(String.isNotBlank(recordId)){
            List<Grants__c> grantList = [SELECT Id,Is_Admin__c,Is_PDF_Generated__c FROM Grants__c WHERE Id =: recordId];
            if(!grantList.isEmpty()){
                grantList[0].Applicant_PDF_URL__c = '';
                grantList[0].Is_Admin__c = false;
                update grantList;
                Id batchJobId = Database.executeBatch(new BatchCreateGrantPDF(recordId), 1);
                return true;
            }
        }
        return false;
    }
}