force-app/main/default/objects/OTP_Verification__c/OTP_Verification__c.object-meta.xml
<CustomObject>
    <label>OTP Verification</label>
    <nameField>
        <displayFormat>OTPV-{000}</displayFormat>
        <label>OTP Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OTP Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OTP_Verification__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <label>OTP</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OTP_Verification__c/fields/Valid__c.field-meta.xml
<CustomField>
    <fullName>Valid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OTPVerificationHandler.cls
public class OTPVerificationHandler {
    
    // Generates a 6-digit OTP and sets Valid__c to true
    public static void generateOTP(List<OTP_Verification__c> newRecords) {
        for(OTP_Verification__c otpRec : newRecords) {
            // Generate a random number between 100000 and 999999
            Integer randomOTP = Math.round(Math.random() * (999999 - 100000)) + 100000;
            otpRec.OTP__c = randomOTP;
            otpRec.Valid__c = true;
        }
    }

    public static void sendOTPEmails(List<OTP_Verification__c> newRecords) {

        List<Id> otpIds = new List<Id>();

        for (OTP_Verification__c otpRec : newRecords) {

            if (String.isBlank(otpRec.Email__c)) {
                continue;
            }

            otpIds.add(otpRec.Id);
        }

        if (otpIds.isEmpty()) {
            return;
        }

        System.enqueueJob(
            new EmailNotificationQueueable(
                'OTP_VERIFICATION',
                otpIds,
                'OTP_Verification_Email'
            )
        );
    }
}