force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Applications</label>
    <nameField>
        <displayFormat>IA-{0000}</displayFormat>
        <label>Applications No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Name_of_applicant__c.field-meta.xml
<CustomField>
    <fullName>Name_of_applicant__c</fullName>
    <label>Name of applicant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pre-Submission</fullName>
            </value>
            <value>
                <fullName>Post-Submission</fullName>
            </value>
            <value>
                <fullName>Awaited Signatory Approval</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Defered</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
                <isActive>false</isActive>
                <label>Deleted</label>
            </value>
            <value>
                <fullName>Modifying</fullName>
                <isActive>false</isActive>
                <label>Modifying</label>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
                <isActive>false</isActive>
                <label>Pre-Approved</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
                <isActive>false</isActive>
                <label>Submission Failed</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
                <isActive>false</isActive>
                <label>Under Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pre-Submission</fullName>
            </value>
            <value>
                <fullName>Post-Submission</fullName>
            </value>
            <value>
                <fullName>Awaited Signatory Approval</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deffered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
                <isActive>false</isActive>
                <label>Deleted</label>
            </value>
            <value>
                <fullName>Modifying</fullName>
                <isActive>false</isActive>
                <label>Modifying</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
                <isActive>false</isActive>
                <label>Under Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IRMI INORMS Travel Grant Application Form</fullName>
            </value>
            <value>
                <fullName>IRMI RM Fellowship Application Form</fullName>
            </value>
            <value>
                <fullName>IRMI RM Grant Application Form</fullName>
            </value>
            <value>
                <fullName>Clinical Research Centres</fullName>
            </value>
            <value>
                <fullName>Team Science Grants</fullName>
            </value>
            <value>
                <fullName>Clinical and Public Health -Early Career Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Clinical and Public Health - Intermediate Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Clinical and Public Health -Senior Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Early Career Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Intermediate Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Senior Fellowship Full applications</fullName>
            </value>
            <value>
                <fullName>Prelim forms have only numbers</fullName>
            </value>
            <value>
                <fullName>Programme Award Application Form</fullName>
            </value>
            <value>
                <fullName>Affordable Approaches to Cancer</fullName>
            </value>
            <value>
                <fullName>Clinical/Public Health Research Centers(CRC)</fullName>
            </value>
            <value>
                <fullName>Team Science Grants (TSG)</fullName>
            </value>
            <value>
                <fullName>INROMS Travel Grant</fullName>
                <isActive>false</isActive>
                <label>INROMS Travel Grant</label>
            </value>
            <value>
                <fullName>IRMIRM Fellowships</fullName>
                <isActive>false</isActive>
                <label>IRMIRM Fellowships</label>
            </value>
            <value>
                <fullName>IRMIRM grants</fullName>
                <isActive>false</isActive>
                <label>IRMIRM grants</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ICAP_AllASchemeController_Test.cls
@isTest
public class ICAP_AllASchemeController_Test {
    public static testmethod void sampleTest(){
        List<Scheme__c> List_scm= new List<Scheme__c>();
        Scheme__c sc= new Scheme__c();
        sc.Name='Masthan';
        sc.Type__c='IRMI RM Grant Application Form';
        insert sc;
        List_scm.add(sc);
        List<Application__c> AppList= new List<Application__c>();
        Application__c appi= new Application__c();
        appi.Name_of_applicant__c='Masthan';
        appi.Status__c='Open';
        insert appi;
        AppList.add(appi);
        ICAP_AllASchemeController.ApplicationGenerateFile(appi.Id);
        ICAP_AllASchemeController.getAllApplicationRecordTypes();
        ICAP_AllASchemeController.getAllScheme();
        ICAP_AllASchemeController.getLoadLayout(appi.Id);

    }
}