force-app/main/default/objects/Additional_Partcipant__c/Additional_Partcipant__c.object-meta.xml
<CustomObject>
    <label>Additional Partcipant</label>
    <nameField>
        <displayFormat>ADP-{00000}</displayFormat>
        <label>Additional Partcipant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Partcipants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Partcipant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Additional Partcipants</relationshipLabel>
    <relationshipName>Additional_Partcipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TRIM(
  IF(ISBLANK(TEXT(Title__c)), &quot;&quot;, TEXT(Title__c) &amp; &quot; &quot;) &amp;
  IF(ISBLANK(First_Name__c), &quot;&quot;, First_Name__c &amp; &quot; &quot;) &amp;
  BLANKVALUE(Last_Name__c, &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Additional Partcipants</relationshipLabel>
    <relationshipName>Additional_Partcipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Proposal_Id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Id__c</fullName>
    <formula>IF(
    ISBLANK(Proposal__c),
    &quot;&quot;,
    Proposal__r.Proposal_Id__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposal Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Proposal_Association__c/Applicant_Proposal_Association__c.object-meta.xml
<CustomObject>
    <label>Applicant Proposal Association</label>
    <nameField>
        <displayFormat>APA -{00000}</displayFormat>
        <label>Applicant Proposal Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Proposal Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Proposal_Association__c/fields/Abstract_Ongoing__c.field-meta.xml
<CustomField>
    <fullName>Abstract_Ongoing__c</fullName>
    <description>Abstracts for ongoing grants and fellowships</description>
    <inlineHelpText>Abstracts for ongoing grants and fellowships</inlineHelpText>
    <label>Abstract(Ongoing)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Applicant_Proposal_Association__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applicant Proposal Associations</relationshipLabel>
    <relationshipName>Applicant_Proposal_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Proposal_Association__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Applicant Proposal Associations</relationshipLabel>
    <relationshipName>Applicant_Proposal_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Abstract_of_proposed_work__c.field-meta.xml
<CustomField>
    <fullName>Abstract_of_proposed_work__c</fullName>
    <label>Abstract of proposed work</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Grand_Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Grand_Total_Cost__c</fullName>
    <label>Grand Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Outline_of_proposed_research__c.field-meta.xml
<CustomField>
    <fullName>Outline_of_proposed_research__c</fullName>
    <description>Outline: 1. Background and identified research gaps 2. Research questions/objectives/aims 3. Approaches 4. Expected Outcomes</description>
    <inlineHelpText>Outline of proposed research</inlineHelpText>
    <label>Outline of proposed research</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Proposal_Id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Id__c</fullName>
    <label>Proposal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Amount__c</fullName>
    <label>Requested Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Research_Title__c.field-meta.xml
<CustomField>
    <fullName>Research_Title__c</fullName>
    <label>Research Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Proposal_Participant_Association__c/Proposal_Participant_Association__c.object-meta.xml
<CustomObject>
    <label>Proposal Participant Association</label>
    <nameField>
        <displayFormat>PPA-{00000}</displayFormat>
        <label>Proposal Participant Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Participant Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal_Participant_Association__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Proposal Participant Associations</relationshipLabel>
    <relationshipName>Proposal_Participant_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal_Participant_Association__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Proposal Participant Associations</relationshipLabel>
    <relationshipName>Proposal_Participant_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/Reviewer__c.object-meta.xml
<CustomObject>
    <label>Reviewer</label>
    <nameField>
        <displayFormat>R-{000}</displayFormat>
        <label>Reviewer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reviewers</relationshipLabel>
    <relationshipName>Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reviewer_Mapping__c/Reviewer_Mapping__c.object-meta.xml
<CustomObject>
    <label>Reviewer Mapping</label>
    <nameField>
        <displayFormat>RM-{000}</displayFormat>
        <label>Reviewer Mapping</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Mapping</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reviewer_Mapping__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Reviewer Mapping</relationshipLabel>
    <relationshipName>Reviewer_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reviewer_Mapping__c/fields/Proposal_Id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Id__c</fullName>
    <formula>IF(
    ISBLANK(Proposal__r.Proposal_Id__c),
    &quot;&quot;,
    Proposal__r.Proposal_Id__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposal Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reviewer_Mapping__c/fields/Reviewer__c.field-meta.xml
<CustomField>
    <fullName>Reviewer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>Reviewer__c</referenceTo>
    <relationshipLabel>Reviewer Mapping</relationshipLabel>
    <relationshipName>Reviewer_Mapping</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/WOHI_Collaboration__c.object-meta.xml
<CustomObject>
    <label>WOHI-Collaboration</label>
    <nameField>
        <displayFormat>WC-{000}</displayFormat>
        <label>WOHI-Collaboration</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WOHI-Collaboration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Applicant_Proposal_Association__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Proposal_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Proposal Association</label>
    <referenceTo>Applicant_Proposal_Association__c</referenceTo>
    <relationshipLabel>WOHI-Collaboration</relationshipLabel>
    <relationshipName>WOHI_Collaboration</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Current_Position__c.field-meta.xml
<CustomField>
    <fullName>Current_Position__c</fullName>
    <label>Current Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TRIM(
IF(ISBLANK(TEXT(Title__c)), &quot;&quot;, TEXT(Title__c) &amp; &quot; &quot;) &amp;
IF(ISBLANK(FirstName__c), &quot;&quot;, FirstName__c&amp; &quot; &quot;) &amp;
BLANKVALUE(Last_Name__c, &quot;&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles_External_Participants</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WOHI_Collaboration__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WOHI</fullName>
            </value>
            <value>
                <fullName>Collaborator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewerMappingProposalAPI.cls
@RestResource(urlMapping='/reviewerMappingProposal/*')
global without sharing class ReviewerMappingProposalAPI {

    @HttpGet
    global static ResponseWrapper getProposalByReviewerMapping() {
        ResponseWrapper response = new ResponseWrapper();

        try {
            RestRequest req = RestContext.request;
            String reviewerMappingId = req.params.get('reviewerMappingId');
            String apaId = req.params.get('apaId');

            if (String.isBlank(reviewerMappingId) && String.isBlank(apaId)) {
                response.success = false;
                response.message = 'Provide either reviewerMappingId or apaId';
                return response;
            }

            Id proposalId;

            if (String.isNotBlank(apaId)) {
                // ---- Use provided APA Id to resolve proposal and contact ---- //
                List<Applicant_Proposal_Association__c> apas = [
                    SELECT Id, Proposal__c, Contact__c,
                           Contact__r.Salutation, Contact__r.Title, Contact__r.Title__c,
                           Contact__r.Name, Contact__r.Account.Name,
                           Proposal__r.Proposal_Id__c,
                           Proposal__r.Project_Title__c,
                           Proposal__r.Research_Title__c,
                           Proposal__r.Outline_of_proposed_research__c,
                           Proposal__r.Grand_Total_Cost__c,
                           Abstract_Ongoing__c
                    FROM Applicant_Proposal_Association__c
                    WHERE Id = :apaId
                    LIMIT 1
                ];

                if (apas.isEmpty()) {
                    response.success = false;
                    response.message = 'No Applicant Proposal Association found for the given apaId';
                    return response;
                }

                Applicant_Proposal_Association__c apa = apas[0];
                if (apa.Proposal__c == null) {
                    response.success = false;
                    response.message = 'No Proposal linked to the given apaId';
                    return response;
                }

                proposalId = apa.Proposal__c;

                ProposalWrapper proposal = new ProposalWrapper();
                proposal.proposalRecordId = apa.Proposal__c;
                proposal.proposalId = apa.Proposal__r.Proposal_Id__c;
                proposal.projectTitle = apa.Proposal__r.Project_Title__c;
                proposal.researchTitle = apa.Proposal__r.Research_Title__c;
                proposal.abstractText = String.isNotBlank(apa.Proposal__r.Outline_of_proposed_research__c)
                    ? apa.Proposal__r.Outline_of_proposed_research__c
                    : apa.Abstract_Ongoing__c;
                proposal.requestedAmount = apa.Proposal__r.Grand_Total_Cost__c;
                response.proposal = proposal;

                if (apa.Contact__r != null) {
                    ContactWrapper cw = new ContactWrapper();
                    String title = resolveTitle(apa.Contact__r);
                    cw.title = title;
                    cw.name = buildDisplayName(apa.Contact__r, title);
                    cw.accountName = apa.Contact__r.Account != null ? apa.Contact__r.Account.Name : null;
                    response.applicantContact = cw;
                }
            } else {
                // ---- Use Reviewer Mapping Id to resolve proposal ----
                List<Reviewer_Mapping__c> mappings = [
                    SELECT Id, Reviewer__c, Proposal__c,
                           Proposal__r.Proposal_Id__c,
                           Proposal__r.Project_Title__c,
                           Proposal__r.Research_Title__c,
                           Proposal__r.Outline_of_proposed_research__c,
                           Proposal__r.Grand_Total_Cost__c
                    FROM Reviewer_Mapping__c
                    WHERE Id = :reviewerMappingId
                    LIMIT 1
                ];

                if (mappings.isEmpty()) {
                    response.success = false;
                    response.message = 'No Reviewer Mapping found for the given reviewerMappingId';
                    return response;
                }

                Reviewer_Mapping__c mapping = mappings[0];
                response.reviewerMappingId = mapping.Id;

                if (mapping.Proposal__c == null) {
                    response.success = false;
                    response.message = 'No Proposal linked to the given Reviewer Mapping';
                    return response;
                }

                proposalId = mapping.Proposal__c;

                ProposalWrapper proposal = new ProposalWrapper();
                proposal.proposalRecordId = mapping.Proposal__c;
                proposal.proposalId = mapping.Proposal__r.Proposal_Id__c;
                proposal.projectTitle = mapping.Proposal__r.Project_Title__c;
                proposal.researchTitle = mapping.Proposal__r.Research_Title__c;
                proposal.requestedAmount = mapping.Proposal__r.Grand_Total_Cost__c;

                // ---- First Applicant Proposal Association and its Contact ---- //
                List<Applicant_Proposal_Association__c> apas = [
                    SELECT Id, Contact__c, Contact__r.Salutation, Contact__r.Title, Contact__r.Title__c,
                           Contact__r.Name, Contact__r.Account.Name, Contact__r.Position__c,
                           Abstract_Ongoing__c
                    FROM Applicant_Proposal_Association__c
                    WHERE Proposal__c = :proposalId
                    AND Contact__c != null
                    ORDER BY CreatedDate ASC
                    LIMIT 1
                ];

                Applicant_Proposal_Association__c apa = null;
                if (!apas.isEmpty()) {
                    apa = apas[0];

                    ContactWrapper cw = new ContactWrapper();
                    String title = resolveTitle(apa.Contact__r);
                    cw.title = title;
                    cw.name = buildDisplayName(apa.Contact__r, title);
                    cw.accountName = apa.Contact__r != null && apa.Contact__r.Account != null
                        ? apa.Contact__r.Account.Name
                        : null;
                    cw.position = apa.Contact__r != null ? apa.Contact__r.Position__c : null;
                    response.applicantContact = cw;
                }

                proposal.abstractText = String.isNotBlank(mapping.Proposal__r.Outline_of_proposed_research__c)
                    ? mapping.Proposal__r.Outline_of_proposed_research__c
                    : (apa != null ? apa.Abstract_Ongoing__c : null);
                response.proposal = proposal;
            }

            response.proposalParticipants = getParticipants(proposalId);

            response.success = true;
            response.message = 'Proposal and participant details fetched successfully';
        } catch (Exception e) {
            response.success = false;
            response.message = 'Error: ' + e.getMessage();
        }

        return response;
    }

    /**
     * Returns participants from ALL sources combined into one list
     * (same ParticipantWrapper for every source):
     *   1. Proposal_Participant_Association__c (PPA)
     *   2. Additional_Partcipant__c
     *   3. WOHI_Collaboration__c (linked via Applicant_Proposal_Association__c)
     */
    private static List<ParticipantWrapper> getParticipants(Id proposalId) {
        List<ParticipantWrapper> participants = new List<ParticipantWrapper>();

        // ---- Source 1: PPA ---- //
        List<Proposal_Participant_Association__c> ppaRecords = [
            SELECT Id, Participant__c, Participant__r.Name, Participant__r.Position__c,
                   Participant__r.Account.Name, Roles__c, Proposal__c
            FROM Proposal_Participant_Association__c
            WHERE Proposal__c = :proposalId
            ORDER BY CreatedDate ASC
        ];

        for (Proposal_Participant_Association__c ppa : ppaRecords) {
            ParticipantWrapper pw = new ParticipantWrapper();
            pw.participantName = ppa.Participant__r != null ? ppa.Participant__r.Name : null;
            pw.participantPosition = ppa.Participant__r != null ? ppa.Participant__r.Position__c : null;
            pw.participantOrganization = (ppa.Participant__r != null && ppa.Participant__r.Account != null)
                ? ppa.Participant__r.Account.Name
                : null;
            pw.role = ppa.Roles__c;
            participants.add(pw);
        }

        // ---- Source 2: Additional Participants ---- //
        List<Additional_Partcipant__c> additionalParticipants = [
            SELECT Id, Full_Name__c, Designation__c, Organisation__c, Roles__c
            FROM Additional_Partcipant__c
            WHERE Proposal__c = :proposalId
            ORDER BY CreatedDate ASC
        ];

        for (Additional_Partcipant__c ap : additionalParticipants) {
            ParticipantWrapper pw = new ParticipantWrapper();
            pw.participantName = ap.Full_Name__c;
            pw.participantPosition = ap.Designation__c;
            pw.participantOrganization = ap.Organisation__c;
            pw.role = ap.Roles__c;
            participants.add(pw);
        }

        // ---- Source 3: WOHI Collaborations (linked via APA) ---- //
        List<WOHI_Collaboration__c> wohiRecords = [
            SELECT Id, Full_Name__c, Current_Position__c, Organisation__c, Roles__c,Type__c
            FROM WOHI_Collaboration__c
            WHERE Applicant_Proposal_Association__r.Proposal__c = :proposalId
            ORDER BY CreatedDate ASC
        ];

        for (WOHI_Collaboration__c wc : wohiRecords) {
            ParticipantWrapper pw = new ParticipantWrapper();
            pw.participantName = wc.Full_Name__c;
            pw.participantPosition = wc.Current_Position__c;
            pw.participantOrganization = wc.Organisation__c;
            //pw.role = wc.Type__c == 'Collaborator' ? 'Collaborator' : wc.Roles__c;
            if (wc.Type__c == 'Collaborator') {
                    pw.role = 'Collaborator';
                } else if (wc.Type__c == 'WOHI' && String.isBlank(wc.Roles__c)) {
                    pw.role = 'External Sponsor';
                } else {
                    pw.role = wc.Roles__c;
                }
            participants.add(pw);
        }

        return participants;
    }

    private static String resolveTitle(SObject contact) {
        if (contact == null) return null;

        String salutation = (String) contact.get('Salutation');
        if (String.isNotBlank(salutation)) return salutation;

        String title = (String) contact.get('Title');
        if (String.isNotBlank(title)) return title;

        String titleCustom = (String) contact.get('Title__c');
        if (String.isNotBlank(titleCustom)) return titleCustom;

        return null;
    }

    private static String buildDisplayName(SObject contact, String title) {
        if (contact == null) return null;

        String name = (String) contact.get('Name');
        if (String.isNotBlank(title) && String.isNotBlank(name)) {
            return title + ' ' + name;
        }

        return name;
    }

    global class ResponseWrapper {
        public Boolean success;
        public String message;
        public String reviewerMappingId;
        public ProposalWrapper proposal;
        public ContactWrapper applicantContact;
        public List<ParticipantWrapper> proposalParticipants;
    }

    global class ProposalWrapper {
        public String proposalRecordId;
        public String proposalId;
        public String projectTitle;
        public String researchTitle;
        public String abstractText;
        public Decimal requestedAmount;
    }

    global class ContactWrapper {
        public String title;
        public String name;
        public String position;
        public String accountName;
    }

    global class ParticipantWrapper {
        public String participantName;
        public String participantPosition;
        public String participantOrganization;
        public String role;
    }
}




/*
@RestResource(urlMapping='/reviewerMappingProposal/*')
global without sharing class ReviewerMappingProposalAPI {

    @HttpGet
    global static ResponseWrapper getProposalByReviewerMapping() {
        ResponseWrapper response = new ResponseWrapper();

        try {
            RestRequest req = RestContext.request;
            String reviewerMappingId = req.params.get('reviewerMappingId');
            String apaId = req.params.get('apaId');

            if (String.isBlank(reviewerMappingId) && String.isBlank(apaId)) {
                response.success = false;
                response.message = 'Provide either reviewerMappingId or apaId';
                return response;
            }

            Id proposalId;

            if (String.isNotBlank(apaId)) {
                // ---- Use provided APA Id to resolve proposal and contact ---- //
                List<Applicant_Proposal_Association__c> apas = [
                    SELECT Id, Proposal__c, Contact__c,
                           Contact__r.Salutation, Contact__r.Title, Contact__r.Title__c,
                           Contact__r.Name, Contact__r.Account.Name,
                           Proposal__r.Proposal_Id__c,
                           Proposal__r.Project_Title__c,
                           Proposal__r.Research_Title__c,
                           Proposal__r.Requested_Amount__c,
                           Abstract_Ongoing__c
                    FROM Applicant_Proposal_Association__c
                    WHERE Id = :apaId
                    LIMIT 1
                ];

                if (apas.isEmpty()) {
                    response.success = false;
                    response.message = 'No Applicant Proposal Association found for the given apaId';
                    return response;
                }

                Applicant_Proposal_Association__c apa = apas[0];
                if (apa.Proposal__c == null) {
                    response.success = false;
                    response.message = 'No Proposal linked to the given apaId';
                    return response;
                }

                proposalId = apa.Proposal__c;

                ProposalWrapper proposal = new ProposalWrapper();
                proposal.proposalRecordId = apa.Proposal__c;
                proposal.proposalId = apa.Proposal__r.Proposal_Id__c;
                proposal.projectTitle = apa.Proposal__r.Project_Title__c;
                proposal.researchTitle = apa.Proposal__r.Research_Title__c;
                proposal.abstractText = String.isNotBlank(apa.Proposal__r.Abstract_of_proposed_work__c)
                    ? apa.Proposal__r.Abstract_of_proposed_work__c
                    : apa.Abstract_Ongoing__c ;
                proposal.requestedAmount = apa.Proposal__r.Requested_Amount__c;
                response.proposal = proposal;

                if (apa.Contact__r != null) {
                    ContactWrapper cw = new ContactWrapper();
                    String title = resolveTitle(apa.Contact__r);
                    cw.title = title;
                    cw.name = buildDisplayName(apa.Contact__r, title);
                    cw.accountName = apa.Contact__r.Account != null ? apa.Contact__r.Account.Name : null;
                    response.applicantContact = cw;
                }
            } else {
                // ---- Use Reviewer Mapping Id to resolve proposal ----
                List<Reviewer_Mapping__c> mappings = [
                    SELECT Id, Reviewer__c, Proposal__c,
                           Proposal__r.Proposal_Id__c,
                           Proposal__r.Project_Title__c,
                           Proposal__r.Research_Title__c,
                           Proposal__r.Abstract_of_proposed_work__c,
                           Proposal__r.Requested_Amount__c
                    FROM Reviewer_Mapping__c
                    WHERE Id = :reviewerMappingId
                    LIMIT 1
                ];

                if (mappings.isEmpty()) {
                    response.success = false;
                    response.message = 'No Reviewer Mapping found for the given reviewerMappingId';
                    return response;
                }

                Reviewer_Mapping__c mapping = mappings[0];
                response.reviewerMappingId = mapping.Id;

                if (mapping.Proposal__c == null) {
                    response.success = false;
                    response.message = 'No Proposal linked to the given Reviewer Mapping';
                    return response;
                }

                proposalId = mapping.Proposal__c;

                ProposalWrapper proposal = new ProposalWrapper();
                proposal.proposalRecordId = mapping.Proposal__c;
                proposal.proposalId = mapping.Proposal__r.Proposal_Id__c;
                proposal.projectTitle = mapping.Proposal__r.Project_Title__c;
                proposal.researchTitle = mapping.Proposal__r.Research_Title__c;
                proposal.requestedAmount = mapping.Proposal__r.Requested_Amount__c;

                // ---- First Applicant Proposal Association and its Contact ---- //
                List<Applicant_Proposal_Association__c> apas = [
                    SELECT Id, Contact__c, Contact__r.Salutation, Contact__r.Title, Contact__r.Title__c,
                           Contact__r.Name, Contact__r.Account.Name, Contact__r.Position__c,
                           Abstract_Ongoing__c
                    FROM Applicant_Proposal_Association__c
                    WHERE Proposal__c = :proposalId
                    AND Contact__c != null
                    ORDER BY CreatedDate ASC
                    LIMIT 1
                ];

                Applicant_Proposal_Association__c apa = null;
                if (!apas.isEmpty()) {
                    apa = apas[0];

                    ContactWrapper cw = new ContactWrapper();
                    String title = resolveTitle(apa.Contact__r);
                    cw.title = title;
                    cw.name = buildDisplayName(apa.Contact__r, title);
                    cw.accountName = apa.Contact__r != null && apa.Contact__r.Account != null
                        ? apa.Contact__r.Account.Name
                        : null;
                    cw.position = apa.Contact__r != null ? apa.Contact__r.Position__c : null;
                    response.applicantContact = cw;
                }

                proposal.abstractText = String.isNotBlank(mapping.Proposal__r.Abstract_of_proposed_work__c)
                    ? mapping.Proposal__r.Abstract_of_proposed_work__c
                    : (apa != null ? apa.Abstract_Ongoing__c : null);
                response.proposal = proposal;
            }

            List<Proposal_Participant_Association__c> ppaRecords = [
                SELECT Id, Participant__c, Participant__r.Name, Participant__r.Position__c, Participant__r.Account.Name,
                Roles__c, Proposal__c
                FROM Proposal_Participant_Association__c
                WHERE Proposal__c = :proposalId
                ORDER BY CreatedDate ASC
            ];

            response.proposalParticipants = new List<ParticipantWrapper>();
            for (Proposal_Participant_Association__c ppa : ppaRecords) {
                ParticipantWrapper pw = new ParticipantWrapper();
                // pw.participantAssociationId = ppa.Id;
                // pw.participantId = ppa.Participant__c;
                pw.participantName = ppa.Participant__r != null ? ppa.Participant__r.Name : null;
                pw.participantPosition = ppa.Participant__r != null ? ppa.Participant__r.Position__c : null;
                pw.participantOrganization = ppa.Participant__r != null ? ppa.Participant__r.Account.Name : null;

                pw.role = ppa.Roles__c;
                response.proposalParticipants.add(pw);
            }

            response.success = true;
            response.message = 'Proposal and participant details fetched successfully';
        } catch (Exception e) {
            response.success = false;
            response.message = 'Error: ' + e.getMessage();
        }

        return response;
    }

    private static String resolveTitle(SObject contact) {
        if (contact == null) return null;

        String salutation = (String) contact.get('Salutation');
        if (String.isNotBlank(salutation)) return salutation;

        String title = (String) contact.get('Title');
        if (String.isNotBlank(title)) return title;

        String titleCustom = (String) contact.get('Title__c');
        if (String.isNotBlank(titleCustom)) return titleCustom;

        return null;
    }

    private static String buildDisplayName(SObject contact, String title) {
        if (contact == null) return null;

        String name = (String) contact.get('Name');
        if (String.isNotBlank(title) && String.isNotBlank(name)) {
            return title + ' ' + name;
        }

        return name;
    }

    global class ResponseWrapper {
        public Boolean success;
        public String message;
        public String reviewerMappingId;
        public ProposalWrapper proposal;
        public ContactWrapper applicantContact;
        public List<ParticipantWrapper> proposalParticipants;
    }

    global class ProposalWrapper {
        public String proposalRecordId;
        public String proposalId;
        public String projectTitle;
        public String researchTitle;
        public String abstractText;
        public Decimal requestedAmount;
    }

    global class ContactWrapper {
        public String title;
        public String name;
        public String position;
        public String accountName;
    }

    global class ParticipantWrapper {
        public String participantName;
        public String participantPosition;
        public String participantOrganization;
        public String role;
    }
}
*/