force-app/main/default/objects/Additional_Partcipant__c/Additional_Partcipant__c.object-meta.xml
<CustomObject>
    <label>Additional Partcipant</label>
    <nameField>
        <displayFormat>ADP-{00000}</displayFormat>
        <label>Additional Partcipant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Partcipants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Additional_Partcipant__c/fields/Invitation_Link__c.field-meta.xml
<CustomField>
    <fullName>Invitation_link__c</fullName>
    <label>Invitation link</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Additional Partcipants</relationshipLabel>
    <relationshipName>Additional_Partcipants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Proposal_Id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Id__c</fullName>
    <formula>IF(
    ISBLANK(Proposal__c),
    &quot;&quot;,
    Proposal__r.Proposal_Id__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Proposal Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Additional_Partcipant__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Proposal_Id__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Id__c</fullName>
    <label>Proposal Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Yearly_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yearly Scheme</label>
    <referenceTo>Yearly_Schemes__c</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Yearly_Schemes__c/Yearly_Schemes__c.object-meta.xml
<CustomObject>
    <label>Yearly Schemes</label>
    <nameField>
        <displayFormat>YS-{00000}</displayFormat>
        <label>Yearly Scheme Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yearly Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Refferee_EmailQueueable.cls
public without sharing class Refferee_EmailQueueable 
  implements Queueable, Database.AllowsCallouts {
    private List<Id> additionalParticipantIds;
    private Map<Id, String> invitationLinks;
    private String templateDeveloperName;

    public Refferee_EmailQueueable( List<Id> additionalParticipantIds, Map<Id, String> invitationLinks,
    String templateDeveloperName ) {
        this.additionalParticipantIds = additionalParticipantIds;
        this.invitationLinks =  invitationLinks;
        this.templateDeveloperName = templateDeveloperName;
    }

    public void execute( QueueableContext context ) {
        if (  additionalParticipantIds == null || additionalParticipantIds.isEmpty() ) {
            return;
        }
        List<Additional_Partcipant__c> records = [
            SELECT Id,
                   Title__c,
                   First_Name__c,
                   Proposal__r.Proposal_Id__c,
                   Proposal__r.Yearly_Scheme__r.Scheme__c, 
                   Last_Name__c,
                   Organisation__c,
                   Email__c,
                   Roles__c,
				   Email_Sent__c
            FROM Additional_Partcipant__c
            WHERE Id IN :additionalParticipantIds
        ];
        List<Additional_Partcipant__c> recordsToUpdate =
            new List<Additional_Partcipant__c>();
        for (Additional_Partcipant__c ap : records) {
            if (String.isBlank(ap.Email__c)) {
                continue;
            }
            String invitationLink = invitationLinks.get(ap.Id);
            Map<String, String> mergeValues =
                new Map<String, String>{
                    'Title' => ap.Title__c,
                    'FirstName' => ap.First_Name__c,
                    'LastName' => ap.Last_Name__c,
                    'SchemeName' => ap.Proposal__r.Yearly_Scheme__r.Scheme__c, 
                    'ProposalId' => ap.Proposal__r.Proposal_Id__c,
                    'Organisation' => ap.Organisation__c,
                    'Email' => ap.Email__c,
                    'InvitationLink' => invitationLink
                };
            System.debug('Merge Value===>'+mergeValues);
            Boolean emailSent = false;
            try {
                HttpResponse response =  SESService.sendEmail( ap.Email__c, templateDeveloperName, mergeValues );
                if ( response != null && response.getStatusCode() >= 200 && response.getStatusCode() < 300 ) {
                    emailSent = true;
                    System.debug(  'WOHI invitation email sent successfully. ' +   'Record Id: ' + ap.Id +   ', Email: ' + ap.Email__c + ', Status: ' +  response.getStatusCode());
                } else {
                    System.debug(  'WOHI invitation email failed. ' + 'Record Id: ' + ap.Id + ', Email: ' + ap.Email__c + ', Status: ' + (
                            response == null
                                ? 'NULL'
                                : String.valueOf(
                                    response.getStatusCode()
                                )
                        ) +
                        ', Body: ' +
                        (
                            response == null
                                ? ''
                                : response.getBody()
                        )
                    );
                }
            } catch (Exception ex) {
                System.debug('WOHI invitation email exception. ' +'Record Id: ' + ap.Id + ', Email: ' + ap.Email__c +  ', Error: ' + ex.getMessage());
            }
            recordsToUpdate.add( new Additional_Partcipant__c( Id = ap.Id, 
           // Invitation_Link__c = invitationLink, 
            Email_Sent__c = emailSent ) );
        }
        if (!recordsToUpdate.isEmpty()) {
            update recordsToUpdate;
        }
   }
}