force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Addresses</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>LP1_Institution__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Background__c.field-meta.xml
<CustomField>
    <fullName>Background__c</fullName>
    <label>Background</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>LP1_Institution__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <formula>TEXT(LP1_Institution__r.Pincode__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (1)</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (2)</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator (3)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Institution__c/Institution__c.object-meta.xml
<CustomObject>
    <label>Institution</label>
    <nameField>
        <displayFormat>INS-{000000}</displayFormat>
        <label>Institution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institution__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Institution</fullName>
            </value>
            <value>
                <fullName>Co-Institution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Institution_Categories__c/Institution_Categories__c.object-meta.xml
<CustomObject>
    <label>Institution Categories</label>
    <nameField>
        <label>Institution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institution Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InstitutionTriggerTest.cls
@isTest
public class InstitutionTriggerTest {
  public static testmethod void insit(){
        
        Grants__c g=new Grants__c();
        g.Background__c='Vali';
        insert g;  
      
        Country__c c=new Country__c();
        c.Name='India';
        insert c;
        
        Address__c add=new Address__c();
        add.Billing_City__c='bundi';
        insert add;
        
        Account a=new Account();
        a.name='Abhi';
        a.Department__c='test';
        a.Institution_Categories__c='Hospital';
        a.Country__c=c.id; 
        a.Address__c=add.id; 
        a.City__c='bundi'; 
        a.Pincode__c=9890; 
        insert a;
        
        Institution__c i= new Institution__c();
        i.Type__c='	Lead Institution';
        i.Institution__c=a.id;
        i.Grants__c=g.id;
        insert i;
        
       
        
    }
}