force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Addresses</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/Checklist__c.object-meta.xml
<CustomObject>
    <label>Checklist</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Checklist No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Checklists</relationshipLabel>
    <relationshipName>Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist__c/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigator</label>
    <referenceTo>Investigator__c</referenceTo>
    <relationshipName>CRC_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/Grants__c.object-meta.xml
<CustomObject>
    <label>Grants</label>
    <nameField>
        <displayFormat>GR-{0000}</displayFormat>
        <label>Grant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Grants__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>LP1_Institution__r.Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>LP1_Institution__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Investigator__c.field-meta.xml
<CustomField>
    <fullName>Investigator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Grants</relationshipLabel>
    <relationshipName>Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <formula>TEXT(LP1_Institution__r.Pincode__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pincode</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Pre-Submission</fullName>
            </value>
            <value>
                <fullName>Post-Submission</fullName>
            </value>
            <value>
                <fullName>Awaited Signatory Approval</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ineligible</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Grants__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Professor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Institution__c/Institution__c.object-meta.xml
<CustomObject>
    <label>Institution</label>
    <nameField>
        <displayFormat>INS-{000000}</displayFormat>
        <label>Institution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Institutions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Institution__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Institutions</relationshipLabel>
    <relationshipName>Institutions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Institution__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Disbaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Institution_Categories__c/Institution_Categories__c.object-meta.xml
<CustomObject>
    <label>Institution Categories</label>
    <nameField>
        <label>Institution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institution Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigator__c/Investigator__c.object-meta.xml
<CustomObject>
    <label>Investigator</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Principal Investigator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigator__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Discipline_expertise__c.field-meta.xml
<CustomField>
    <fullName>Discipline_expertise__c</fullName>
    <label>Discipline/Expertise</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipName>Principal_Investigators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Investigators</relationshipLabel>
    <relationshipName>Principal_Investigators</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Investigators_Type__c.field-meta.xml
<CustomField>
    <fullName>Investigators_Type__c</fullName>
    <label>Investigator Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Principal Investigator</fullName>
            </value>
            <value>
                <fullName>Coordinator 1</fullName>
                <isActive>false</isActive>
                <label>Coordinator 1</label>
            </value>
            <value>
                <fullName>Coordinator 2</fullName>
                <isActive>false</isActive>
                <label>Coordinator 2</label>
            </value>
            <value>
                <fullName>Coordinator 3</fullName>
                <isActive>false</isActive>
                <label>Coordinator 3</label>
            </value>
            <value>
                <fullName>Lead Principal Investigator</fullName>
                <isActive>false</isActive>
                <label>Lead Principal Investigator</label>
            </value>
            <value>
                <fullName>Programme Head</fullName>
                <isActive>false</isActive>
                <label>Programme Head</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <length>70</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/ORCID_ID__c.field-meta.xml
<CustomField>
    <fullName>ORCID_ID__c</fullName>
    <label>ORCID ID</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigator__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Professor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Peer_Review_Checklist__c/Peer_Review_Checklist__c.object-meta.xml
<CustomObject>
    <label>Peer Review Checklist</label>
    <nameField>
        <label>Peer Review Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peer Review Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Peer_Review_Checklist__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Peer Review Checklists</relationshipLabel>
    <relationshipName>Peer_Review_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Screening_Committee__c/Screening_Committee__c.object-meta.xml
<CustomObject>
    <label>Screening Committee</label>
    <nameField>
        <label>Screening Committee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Screening Committee</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Screening_Committee__c/fields/Grants__c.field-meta.xml
<CustomField>
    <fullName>Grants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grants</label>
    <referenceTo>Grants__c</referenceTo>
    <relationshipLabel>Screening Committee</relationshipLabel>
    <relationshipName>Screening_Committee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TST_CNT_CheckListForm.cls
@isTest
private class TST_CNT_CheckListForm {
    static testMethod void testCheckListForm() {
    	Grants__c testGrant = new Grants__c();
        insert testGrant;
        
        Country__c testCountry = new Country__c();
        insert testCountry;
        
        Account testAcc = new Account();
        testAcc.Name = 'Test Account';
        testAcc.Department__c = 'test';
        testAcc.Country__c = testCountry.Id;
        testAcc.Address__c = 'test';
        testAcc.City__c = 'test';
        testAcc.Pincode__c = 1234;
        testAcc.Institution_Categories__c = 'Hospital';
        insert testAcc;
        
        Investigator__c testInvestigator = new Investigator__c();
        testInvestigator.Investigators_Type__c = 'Principal Investigator';
        testInvestigator.Grants__c = testGrant.Id;
        testInvestigator.Title__c = 'Dr.';
        testInvestigator.First_Name__c = 'test';
        testInvestigator.Last_Name__c = 'test';
        testInvestigator.Discipline_expertise__c = 'test';
        testInvestigator.Institution__c = testAcc.Id;
        testInvestigator.Nationality__c = 'test';
        testInvestigator.Date_of_Birth__c = Date.today();
        testInvestigator.Gender__c = 'Male';
        testInvestigator.Contact_Number__c = 'test';
        testInvestigator.Email__c = 'test@gmail.com';
        testInvestigator.ORCID_ID__c = '1111-2222-3333-4444';
        testInvestigator.Role__c = 'test';
        insert testInvestigator;
        
        Checklist__c testChecklist = new Checklist__c();
        insert testChecklist;
        CNT_CheckListForm.getCurrentChecklist(String.valueOf(testGrant.id));
        CNT_CheckListForm.saveChecklistRecord(testChecklist, 'Submit');
        
        Peer_Review_Checklist__c testReviewChecklist = new Peer_Review_Checklist__c();
        insert testReviewChecklist;
        CNT_CheckListForm.getCurrentReviewChecklist(String.valueOf(testGrant.id));
        CNT_CheckListForm.saveReviewChecklistRecord(testReviewChecklist, 'Save');
        
        Screening_Committee__c testScreeningReview = new Screening_Committee__c();
        insert testScreeningReview;
        CNT_CheckListForm.getCurrentReviewScreening(String.valueOf(testGrant.id));
        CNT_CheckListForm.saveReviewScreeningRecord(testScreeningReview, 'Submit');
        
        testGrant.Status__c = 'Decline';
        update testGrant;
    }
}