force-app/main/default/objects/Applicant_Proposal_Association__c/Applicant_Proposal_Association__c.object-meta.xml
<CustomObject>
    <label>Applicant Proposal Association</label>
    <nameField>
        <displayFormat>APA -{00000}</displayFormat>
        <label>Applicant Proposal Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Proposal Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Proposal_Association__c/fields/Decision_on_previous_application__c.field-meta.xml
<CustomField>
    <fullName>Decision_on_previous_application__c</fullName>
    <description>Decision on previous application</description>
    <inlineHelpText>Decision on previous application</inlineHelpText>
    <label>Decision on previous application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended for an award</fullName>
            </value>
            <value>
                <fullName>Declined at interview, but resubmission recommended by the Committee</fullName>
            </value>
            <value>
                <fullName>Declined at interview</fullName>
            </value>
            <value>
                <fullName>Declined at shortlisting (i.e., full application was not shortlisted for interview)</fullName>
            </value>
            <value>
                <fullName>Declined at preliminary application stage (i.e., full application was not invited)</fullName>
            </value>
            <value>
                <fullName>I withdrew my full application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Countries</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQN-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Applicant_Proposal_Association__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Proposal_Association__c</fullName>
    <label>Applicant Proposal Association</label>
    <referenceTo>Applicant_Proposal_Association__c</referenceTo>
    <relationshipLabel>Equipments</relationshipLabel>
    <relationshipName>Equipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Year_Required__c.field-meta.xml
<CustomField>
    <fullName>Year_Required__c</fullName>
    <label>Year Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Institution_Categories__c/Institution_Categories__c.object-meta.xml
<CustomObject>
    <label>Institution Categories</label>
    <nameField>
        <label>Institution Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Institution Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Grants__c/Other_Grants__c.object-meta.xml
<CustomObject>
    <label>Other Grants</label>
    <nameField>
        <displayFormat>OG-{00000}</displayFormat>
        <label>Other Grants Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Grants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Other_Grants__c/fields/Applicant_Proposal_Association__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Proposal_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Proposal Association</label>
    <referenceTo>Applicant_Proposal_Association__c</referenceTo>
    <relationshipLabel>Other Grants</relationshipLabel>
    <relationshipName>Other_Grants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Other_Grants__c/fields/Decision_on_previous_application__c.field-meta.xml
<CustomField>
    <fullName>Decision_on_previous_application__c</fullName>
    <label>Decision on previous application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recommended for an award</fullName>
            </value>
            <value>
                <fullName>Declined at interview, but resubmission recommended by the Committee</fullName>
            </value>
            <value>
                <fullName>Declined at interview</fullName>
            </value>
            <value>
                <fullName>Declined at shortlisting (i.e., full application was not shortlisted for interview)</fullName>
            </value>
            <value>
                <fullName>Declined at preliminary application stage (i.e., full application was not invited)</fullName>
            </value>
            <value>
                <fullName>I withdrew my full application</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Proposal_Participant_Association__c/Proposal_Participant_Association__c.object-meta.xml
<CustomObject>
    <label>Proposal Participant Association</label>
    <nameField>
        <displayFormat>PPA-{00000}</displayFormat>
        <label>Proposal Participant Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Participant Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Budget__c/Staff_Budget__c.object-meta.xml
<CustomObject>
    <description>Staff/Material and Consumable/Access Charges</description>
    <label>Staff Budget</label>
    <nameField>
        <displayFormat>SBGT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Budgets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Budget__c/fields/Applicant_Proposal_Association__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Proposal_Association__c</fullName>
    <label>Applicant Proposal Association</label>
    <referenceTo>Applicant_Proposal_Association__c</referenceTo>
    <relationshipLabel>Staff Budgets</relationshipLabel>
    <relationshipName>Staff_Budgets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staff_Budget__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Project Assistant</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Post Doctoral Fellow</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Senior Resident</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Field Worker</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GlobalPicklistValues.cls
// @RestResource(urlMapping='/getGlobalPicklistValues')
// global without sharing class GlobalPicklistValues {
	
//     @HttpGet
//     global static ResponseWrapper getPicklistValues(){
        
//         ResponseWrapper response = new ResponseWrapper();
        
//         Contact.Nationality__c.getDescribe();
        
//         Schema.DescribeFieldResult nationalityFieldResult = Contact.Nationality__c.getDescribe();
//         response.nationalityValues = getSafePicklistValues(nationalityFieldResult);
        
//         Schema.DescribeFieldResult institutionCategoriesFieldResult = Account.Institution_Categories__c.getDescribe();
// 		response.institutionalCategoriesValues = getSafePicklistValues(institutionCategoriesFieldResult);

//         Schema.DescribeFieldResult titleFieldResult = Contact.Title__c.getDescribe();
//         response.titleFieldResultValues = getSafePicklistValues(titleFieldResult);

//         Schema.DescribeFieldResult rolesFieldResult = Proposal_Participant_Association__c.Roles__c.getDescribe();
//         response.rolesValues = getSafePicklistValues(rolesFieldResult);

//         Schema.DescribeFieldResult decisionOnPreviousApplicationFieldResult = Applicant_Proposal_Association__c.Decision_on_previous_application__c.getDescribe();
//         response.decisionOnPreviousApplicationValues = getSafePicklistValues(decisionOnPreviousApplicationFieldResult);


//         Map<String, String> accountMap = new Map<String, String>();
//         for (Account acc : [ SELECT Id, Name FROM Account Where Organization_Status__c='Listed'
//                              ORDER BY Name]) {
//             accountMap.put(acc.Id, acc.Name);
//         }
//         response.accounts = accountMap;

//         return response;
//     }
    
    
//     private static FieldResult getSafePicklistValues(Schema.DescribeFieldResult fieldDescribe){
        
//         FieldResult result = new FieldResult();
        
//         try{    
//             List<String> activeValues = new List<String>();

//             List<Schema.PicklistEntry> nList = fieldDescribe.getPicklistValues();
//             for (Schema.PicklistEntry pickListVal : nList) {
//                 if (pickListVal.isActive()) {
//                     activeValues.add(pickListVal.getLabel()); // Use getValue() for API names
//                 }
//             }
            
//             result.status = 'Success';
//             result.values = activeValues;
            
//         }catch(Exception ex){
//             result.status = 'Error';
//             result.errorMessage = 'Error fetching picklist values: ' + ex.getMessage();
//         }
        
//         return result;
//     }
    
//     global class ResponseWrapper {
//         public FieldResult nationalityValues;
//         public FieldResult institutionalCategoriesValues;
//         public FieldResult titleFieldResultValues;
//         public FieldResult rolesValues;
//         public FieldResult decisionOnPreviousApplicationValues;
//         public Map<String, String> accounts;
//     }
    
//     global class FieldResult {
//         public String status;
//         public String errorMessage;
//         public List<String> values;
//     }   
// }


@RestResource(urlMapping='/getGlobalPicklistValues')
global without sharing class GlobalPicklistValues {

    @HttpGet
    global static ResponseWrapper getPicklistValues() {

        ResponseWrapper response = new ResponseWrapper();

        // Nationality
        Schema.DescribeFieldResult nationalityFieldResult = Contact.Nationality__c.getDescribe();
        response.nationalityValues = getSafePicklistValues(nationalityFieldResult);

        // Institution Categories
        Schema.DescribeFieldResult institutionCategoriesFieldResult = Account.Institution_Categories__c.getDescribe();
        response.institutionalCategoriesValues = getSafePicklistValues(institutionCategoriesFieldResult);

        // Title
        Schema.DescribeFieldResult titleFieldResult = Contact.Title__c.getDescribe();
        response.titleFieldResultValues = getSafePicklistValues(titleFieldResult);

        // Roles (Exclude Applicant)
        Schema.DescribeFieldResult rolesFieldResult = Proposal_Participant_Association__c.Roles__c.getDescribe();
        response.rolesValues = getSafePicklistValues(rolesFieldResult,
            new Set<String>{ 'Applicant' } // API Value
        );

        Schema.DescribeFieldResult jobTitleFieldResult = Staff_Budget__c.Job_Title__c.getDescribe();
        response.jobTitleFieldResultValues = getSafePicklistValues(jobTitleFieldResult);

        Schema.DescribeFieldResult yearFieldResult = Equipment__c.Year_Required__c.getDescribe();
        response.yearFieldResultResultValues = getSafePicklistValues(jobTitleFieldResult);

        // Country
        Schema.DescribeFieldResult countryFieldResult = Contact.Country__c.getDescribe();
        response.countryValues = getSafePicklistValues(countryFieldResult);

        // Decision on Previous Application
        Schema.DescribeFieldResult decisionOnPreviousApplicationFieldResult = Other_Grants__c.Decision_on_previous_application__c.getDescribe();
        response.decisionOnPreviousApplicationValues = getSafePicklistValues(decisionOnPreviousApplicationFieldResult);

        // HostAccounts
        Map<String, String> accountMap = new Map<String, String>();
        for (Account acc : [SELECT Id, Name FROM Account WHERE Organization_Status__c = 'Listed' ORDER BY Name]) {
            accountMap.put(acc.Id, acc.Name);
        }
        response.accounts = accountMap;

        //OrganiZation Accounts
        Map<String, String> organizationMap = new Map<String, String>();
        for (Account acc1 : [SELECT Id, Name FROM Account WHERE Type != 'Host' ORDER BY Name]) {
            organizationMap.put(acc1.Id, acc1.Name);
        }
        response.organizations = organizationMap;


        return response;
    }

    // Default method (No exclusions)
    private static FieldResult getSafePicklistValues(
        Schema.DescribeFieldResult fieldDescribe
    ) {
        return getSafePicklistValues(fieldDescribe, new Set<String>());
    }

    // Overloaded method (Supports exclusions)
    private static FieldResult getSafePicklistValues(
        Schema.DescribeFieldResult fieldDescribe,
        Set<String> excludedValues
    ) {

        FieldResult result = new FieldResult();

        try {
            List<String> activeValues = new List<String>();

            for (Schema.PicklistEntry pickListVal : fieldDescribe.getPicklistValues()) {

                if (pickListVal.isActive()
                    && !excludedValues.contains(pickListVal.getValue())) {

                    // Use getLabel() if you want labels in the response
                    activeValues.add(pickListVal.getLabel());

                    // Or use getValue() if API values are required
                    // activeValues.add(pickListVal.getValue());
                }
            }

            result.status = 'Success';
            result.values = activeValues;

        } catch (Exception ex) {
            result.status = 'Error';
            result.errorMessage = 'Error fetching picklist values: ' + ex.getMessage();
        }

        return result;
    }

    global class ResponseWrapper {
        public FieldResult nationalityValues;
        public FieldResult institutionalCategoriesValues;
        public FieldResult titleFieldResultValues;
        public FieldResult jobTitleFieldResultValues;
        public FieldResult yearFieldResultResultValues;
        public FieldResult rolesValues;
        public FieldResult countryValues;
        public FieldResult decisionOnPreviousApplicationValues;
        public Map<String, String> accounts;
        public Map<String, String> organizations;
    }

    global class FieldResult {
        public String status;
        public String errorMessage;
        public List<String> values;
    }
}