force-app/main/default/objects/Applicant_Proposal_Association__c/Applicant_Proposal_Association__c.object-meta.xml
<CustomObject>
    <label>Applicant Proposal Association</label>
    <nameField>
        <displayFormat>APA -{00000}</displayFormat>
        <label>Applicant Proposal Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicant Proposal Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme_Section__c/Scheme_Section__c.object-meta.xml
<CustomObject>
    <label>Scheme Section</label>
    <nameField>
        <displayFormat>SS-{000}</displayFormat>
        <label>Scheme Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheme Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme_Section__c/fields/Applicant_Proposal_Association__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Proposal_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Proposal Association</label>
    <referenceTo>Applicant_Proposal_Association__c</referenceTo>
    <relationshipLabel>Scheme Sections</relationshipLabel>
    <relationshipName>Scheme_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheme_Section__c/fields/Reopen_Status__c.field-meta.xml
<CustomField>
    <fullName>Reopen_Status__c</fullName>
    <label>Reopen Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reopen</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchemeSectionTriggerHandler.cls
public class SchemeSectionTriggerHandler {

    private static final String EMAIL_TEMPLATE_DEVELOPER_NAME =
        'Reopen_Section_Detail';
    
        public static void handleAfterUpdateofReopen(
            List<Scheme_Section__c> newRecords,
            Map<Id, Scheme_Section__c> oldMap
        ) {
    
            Set<Id> reopenedSectionIds =
                new Set<Id>();
    
            for (Scheme_Section__c section : newRecords) {
    
                Scheme_Section__c oldSection =
                    oldMap.get(section.Id);
    
                if (
                    section.Reopen_Status__c == 'Reopen' &&
                    oldSection != null &&
                    oldSection.Reopen_Status__c != 'Reopen' &&
                    section.Applicant_Proposal_Association__c != null
                ) {
    
                    reopenedSectionIds.add(section.Id);
                }
            }
    
            if (reopenedSectionIds.isEmpty()) {
                return;
            }
            system.debug('Line 33-===>');
    
            sendReopenNotificationEmails(
                reopenedSectionIds
            );
        }
    
    
        private static void sendReopenNotificationEmails(
            Set<Id> sectionIds
        ) {
    
            System.enqueueJob(
                new EmailNotificationQueueable(
                    'SCHEME_SECTION_REOPEN',
                    new List<Id>(sectionIds),
                    'Reopen_Section_Detail'
                )
            );
        }
}