force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme__c/fields/Extension__c.field-meta.xml
<CustomField>
    <fullName>Extension__c</fullName>
    <label>Extension</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Scheme_Type__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Type__c</fullName>
    <label>Scheme Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fellowship</fullName>
            </value>
            <value>
                <fullName>Grant</fullName>
            </value>
            <value>
                <fullName>Research Management Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pre-Submission</fullName>
            </value>
            <value>
                <fullName>Post-Submission</fullName>
            </value>
            <value>
                <fullName>Awaited Signatory Approval</fullName>
            </value>
            <value>
                <fullName>Pending Submission</fullName>
            </value>
            <value>
                <fullName>Submission Failed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pre-Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Deffered</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
                <isActive>false</isActive>
                <label>Deleted</label>
            </value>
            <value>
                <fullName>Modifying</fullName>
                <isActive>false</isActive>
                <label>Modifying</label>
            </value>
            <value>
                <fullName>Returned</fullName>
                <isActive>false</isActive>
                <label>Returned</label>
            </value>
            <value>
                <fullName>Under Review</fullName>
                <isActive>false</isActive>
                <label>Under Review</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheme__c/fields/Total_Requested_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Requested_Amount__c</fullName>
    <label>Total Requested Amount</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllSchemes.cls
@RestResource(urlMapping='/getActiveSchemes')
global without sharing class GetAllSchemes {
    
    @HttpGet
    global static ResponseWrapper getAllSchemes(){

        List<SchemeWrapper> schemesWrapper = new List<SchemeWrapper>();
        ResponseWrapper response = new ResponseWrapper();

        try {
            List<Scheme__c> schemes = [
                SELECT Id, Name, Scheme_Type__c, Duration__c, Outcome__c, Total_Requested_Amount__c, Status__c, Start_Date__c, End_Date__c, 
                Extension__c
                FROM Scheme__c 
                WHERE Status__c = 'Open' 
                AND End_Date__c >=: System.today() 
            ];

            if(schemes.isEmpty()){
                response.status = 'Error';
                response.message = 'No schemes found';
                response.success = false;
                return response;
            }

            for(Scheme__c scheme : schemes){
                SchemeWrapper schemeWrapper = new SchemeWrapper();
                schemeWrapper.schemeId = scheme.Id;
                schemeWrapper.schemeName = scheme.Name;
                schemeWrapper.schemeType = scheme.Scheme_Type__c;
                schemeWrapper.duration = scheme.Duration__c;
                schemeWrapper.outcome = scheme.Outcome__c;
                schemeWrapper.startDate = scheme.Start_Date__c;
                schemeWrapper.endDate = scheme.End_Date__c;
                schemeWrapper.extension = scheme.Extension__c;
                schemesWrapper.add(schemeWrapper);
            }
            response.schemes = schemesWrapper;
            response.status  = 'Success';
            response.message = 'Schemes fetched successfully';
            response.success = true;
            return response;
        }
        catch(Exception ex){
            response.status = 'Error';
            response.message = 'An error occurred while fetching schemes: ' + ex.getMessage();
            response.success = false;
            return response;
        }
    }
    

    global class ResponseWrapper {
        public List<SchemeWrapper> schemes;
        public String status;
        public String message;
        public Boolean success;
    }

    global class SchemeWrapper {
        public String schemeId;
        public String schemeName;
        public String schemeType;
        public Decimal duration;
        public String outcome;
        public Date startDate;
        public Date endDate;
        public String extension;
    }
}