force-app/main/default/objects/Scheme__c/Scheme__c.object-meta.xml
<CustomObject>
    <label>Scheme</label>
    <nameField>
        <label>Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme_Items__c/Scheme_Items__c.object-meta.xml
<CustomObject>
    <label>Sub-Scheme</label>
    <nameField>
        <label>Sub-Scheme Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub-Schemes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheme_Items__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <description>Child of Schemes</description>
    <label>Scheme</label>
    <referenceTo>Scheme__c</referenceTo>
    <relationshipName>Scheme_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Year__c/Year__c.object-meta.xml
<CustomObject>
    <label>Year</label>
    <nameField>
        <label>Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Year__c/fields/Is_Current_Year__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Year__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current Year</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Yearly_Schemes__c/Yearly_Schemes__c.object-meta.xml
<CustomObject>
    <label>Yearly Schemes</label>
    <nameField>
        <displayFormat>YS-{00000}</displayFormat>
        <label>Yearly Scheme Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Yearly Schemes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Yearly_Schemes__c/fields/Scheme__c.field-meta.xml
<CustomField>
    <fullName>Scheme__c</fullName>
    <formula>Scheme_Items__r.Scheme__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Scheme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Yearly_Schemes__c/fields/Scheme_Items__c.field-meta.xml
<CustomField>
    <fullName>Scheme_Items__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub-Schemes</label>
    <referenceTo>Scheme_Items__c</referenceTo>
    <relationshipLabel>Yearly Schemes</relationshipLabel>
    <relationshipName>Yearly_Schemes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Yearly_Schemes__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Year</label>
    <referenceTo>Year__c</referenceTo>
    <relationshipName>Yearly_Schemes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EligibilityEvaluationServiceTest.cls
@IsTest
private class EligibilityEvaluationServiceTest {

    @IsTest
    static void parseFormulaExtractsMultipleConditions() {
        List<EligibilityFormulaParser.ParsedCondition> parsedConditions = EligibilityFormulaParser.parse(
            'Contact.Research_Experience_After_Viva_Date_Yrs__c > 6 AND Contact.Qualifying_Degree__c = PhD'
        );

        System.assertEquals(2, parsedConditions.size());
        System.assertEquals('Contact', parsedConditions[0].objectApiName);
        System.assertEquals('Research_Experience_After_Viva_Date_Yrs__c', parsedConditions[0].fieldApiName);
        System.assertEquals('>', parsedConditions[0].operatorToken);
        System.assertEquals('6', parsedConditions[0].expectedValue);
        System.assertEquals('AND', parsedConditions[0].logicalOperator);
        System.assertEquals('Qualifying_Degree__c', parsedConditions[1].fieldApiName);
        System.assertEquals('PhD', parsedConditions[1].expectedValue);
    }

    @IsTest
    static void parseFormulaIgnoresPeriodsInsideQuotedValues() {
        List<EligibilityFormulaParser.ParsedCondition> parsedConditions = EligibilityFormulaParser.parse(
            'Contact.Qualifying_Degree__c = \'B.Sc\' OR Contact.Qualifying_Degree__c = \'M.D.\''
        );

        System.assertEquals(2, parsedConditions.size());
        System.assertEquals('B.Sc', parsedConditions[0].expectedValue);
        System.assertEquals('M.D.', parsedConditions[1].expectedValue);
    }

    @IsTest
    static void evaluateYearlySchemeReturnsNotConfiguredWhenNoCriteria() {
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Contact testContact = new Contact(
            LastName = 'Applicant',
            AccountId = testAccount.Id,
            Qualifying_Degree__c = 'PhD',
            Research_Experience_After_Viva_Date_Yrs__c = 8
        );
        insert testContact;

        Year__c testYear = new Year__c(
            Name = '2026',
            Is_Active__c = true,
            Is_Current_Year__c = true
        );
        insert testYear;

        Scheme__c testScheme = new Scheme__c(
            Name = 'Test Scheme',
            is_Active__c = true
        );
        insert testScheme;

        Scheme_Items__c testSchemeItem = new Scheme_Items__c(
            Name = 'Item 1',
            Scheme__c = testScheme.Id,
            Is_Active__c = true
        );
        insert testSchemeItem;

        Yearly_Schemes__c testYearlyScheme = new Yearly_Schemes__c(
            Year__c = testYear.Id,
            Scheme_Items__c = testSchemeItem.Id,
            Is_Active__c = true
        );
        insert testYearlyScheme;

        Test.startTest();
        EligibilityEvaluationService.EligibilityEvaluationResult result =
            EligibilityEvaluationService.evaluateYearlyScheme(testContact.Id, testYearlyScheme.Id);
        Test.stopTest();

        System.assertEquals(false, result.hasConfiguredCriteria);
        System.assertEquals(true, result.canApply);
    }
}